// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// BeatManagerMock is a mock implementation of scheduler.BeatManager.
//
//	func TestSomethingThatUsesBeatManager(t *testing.T) {
//
//		// make and configure a mocked scheduler.BeatManager
//		mockedBeatManager := &BeatManagerMock{
//			DeleteOrphanBeatsFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the DeleteOrphanBeats method")
//			},
//		}
//
//		// use mockedBeatManager in code that requires scheduler.BeatManager
//		// and then make assertions.
//
//	}
type BeatManagerMock struct {
	// DeleteOrphanBeatsFunc mocks the DeleteOrphanBeats method.
	DeleteOrphanBeatsFunc func(ctx context.Context) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteOrphanBeats holds details about calls to the DeleteOrphanBeats method.
		DeleteOrphanBeats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockDeleteOrphanBeats sync.RWMutex
}

// DeleteOrphanBeats calls DeleteOrphanBeatsFunc.
func (mock *BeatManagerMock) DeleteOrphanBeats(ctx context.Context) (int64, error) {
	if mock.DeleteOrphanBeatsFunc == nil {
		panic("BeatManagerMock.DeleteOrphanBeatsFunc: method is nil but BeatManager.DeleteOrphanBeats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteOrphanBeats.Lock()
	mock.calls.DeleteOrphanBeats = append(mock.calls.DeleteOrphanBeats, callInfo)
	mock.lockDeleteOrphanBeats.Unlock()
	return mock.DeleteOrphanBeatsFunc(ctx)
}

// DeleteOrphanBeatsCalls gets all the calls that were made to DeleteOrphanBeats.
// Check the length with:
//
//	len(mockedBeatManager.DeleteOrphanBeatsCalls())
func (mock *BeatManagerMock) DeleteOrphanBeatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteOrphanBeats.RLock()
	calls = mock.calls.DeleteOrphanBeats
	mock.lockDeleteOrphanBeats.RUnlock()
	return calls
}
