// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/umputun/newscope/pkg/domain"
)

// BeatStoreMock is a mock implementation of scheduler.BeatStore.
//
//	func TestSomethingThatUsesBeatStore(t *testing.T) {
//
//		// make and configure a mocked scheduler.BeatStore
//		mockedBeatStore := &BeatStoreMock{
//			AttachOrSeedFunc: func(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error) {
//				panic("mock out the AttachOrSeed method")
//			},
//			GetUnbeatItemsFunc: func(ctx context.Context, limit int) ([]domain.BeatCandidate, error) {
//				panic("mock out the GetUnbeatItems method")
//			},
//		}
//
//		// use mockedBeatStore in code that requires scheduler.BeatStore
//		// and then make assertions.
//
//	}
type BeatStoreMock struct {
	// AttachOrSeedFunc mocks the AttachOrSeed method.
	AttachOrSeedFunc func(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error)

	// GetUnbeatItemsFunc mocks the GetUnbeatItems method.
	GetUnbeatItemsFunc func(ctx context.Context, limit int) ([]domain.BeatCandidate, error)

	// calls tracks calls to the methods.
	calls struct {
		// AttachOrSeed holds details about calls to the AttachOrSeed method.
		AttachOrSeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item domain.BeatCandidate
			// Threshold is the threshold argument value.
			Threshold float64
			// Window is the window argument value.
			Window time.Duration
			// MaxMembers is the maxMembers argument value.
			MaxMembers int
		}
		// GetUnbeatItems holds details about calls to the GetUnbeatItems method.
		GetUnbeatItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockAttachOrSeed   sync.RWMutex
	lockGetUnbeatItems sync.RWMutex
}

// AttachOrSeed calls AttachOrSeedFunc.
func (mock *BeatStoreMock) AttachOrSeed(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error) {
	if mock.AttachOrSeedFunc == nil {
		panic("BeatStoreMock.AttachOrSeedFunc: method is nil but BeatStore.AttachOrSeed was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Item       domain.BeatCandidate
		Threshold  float64
		Window     time.Duration
		MaxMembers int
	}{
		Ctx:        ctx,
		Item:       item,
		Threshold:  threshold,
		Window:     window,
		MaxMembers: maxMembers,
	}
	mock.lockAttachOrSeed.Lock()
	mock.calls.AttachOrSeed = append(mock.calls.AttachOrSeed, callInfo)
	mock.lockAttachOrSeed.Unlock()
	return mock.AttachOrSeedFunc(ctx, item, threshold, window, maxMembers)
}

// AttachOrSeedCalls gets all the calls that were made to AttachOrSeed.
// Check the length with:
//
//	len(mockedBeatStore.AttachOrSeedCalls())
func (mock *BeatStoreMock) AttachOrSeedCalls() []struct {
	Ctx        context.Context
	Item       domain.BeatCandidate
	Threshold  float64
	Window     time.Duration
	MaxMembers int
} {
	var calls []struct {
		Ctx        context.Context
		Item       domain.BeatCandidate
		Threshold  float64
		Window     time.Duration
		MaxMembers int
	}
	mock.lockAttachOrSeed.RLock()
	calls = mock.calls.AttachOrSeed
	mock.lockAttachOrSeed.RUnlock()
	return calls
}

// GetUnbeatItems calls GetUnbeatItemsFunc.
func (mock *BeatStoreMock) GetUnbeatItems(ctx context.Context, limit int) ([]domain.BeatCandidate, error) {
	if mock.GetUnbeatItemsFunc == nil {
		panic("BeatStoreMock.GetUnbeatItemsFunc: method is nil but BeatStore.GetUnbeatItems was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetUnbeatItems.Lock()
	mock.calls.GetUnbeatItems = append(mock.calls.GetUnbeatItems, callInfo)
	mock.lockGetUnbeatItems.Unlock()
	return mock.GetUnbeatItemsFunc(ctx, limit)
}

// GetUnbeatItemsCalls gets all the calls that were made to GetUnbeatItems.
// Check the length with:
//
//	len(mockedBeatStore.GetUnbeatItemsCalls())
func (mock *BeatStoreMock) GetUnbeatItemsCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockGetUnbeatItems.RLock()
	calls = mock.calls.GetUnbeatItems
	mock.lockGetUnbeatItems.RUnlock()
	return calls
}
