// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/umputun/newscope/pkg/domain"
)

// BeatStoreMock is a mock implementation of scheduler.BeatStore.
//
//	func TestSomethingThatUsesBeatStore(t *testing.T) {
//
//		// make and configure a mocked scheduler.BeatStore
//		mockedBeatStore := &BeatStoreMock{
//			AppendTitleRevisionFunc: func(ctx context.Context, beatID int64, title string, summary string) error {
//				panic("mock out the AppendTitleRevision method")
//			},
//			AttachOrSeedFunc: func(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error) {
//				panic("mock out the AttachOrSeed method")
//			},
//			GetUnbeatItemsFunc: func(ctx context.Context, limit int) ([]domain.BeatCandidate, error) {
//				panic("mock out the GetUnbeatItems method")
//			},
//			ListPendingMergeFunc: func(ctx context.Context, limit int) ([]domain.Beat, error) {
//				panic("mock out the ListPendingMerge method")
//			},
//			SaveCanonicalFunc: func(ctx context.Context, beatID int64, c domain.BeatCanonical) error {
//				panic("mock out the SaveCanonical method")
//			},
//		}
//
//		// use mockedBeatStore in code that requires scheduler.BeatStore
//		// and then make assertions.
//
//	}
type BeatStoreMock struct {
	// AppendTitleRevisionFunc mocks the AppendTitleRevision method.
	AppendTitleRevisionFunc func(ctx context.Context, beatID int64, title string, summary string) error

	// AttachOrSeedFunc mocks the AttachOrSeed method.
	AttachOrSeedFunc func(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error)

	// GetUnbeatItemsFunc mocks the GetUnbeatItems method.
	GetUnbeatItemsFunc func(ctx context.Context, limit int) ([]domain.BeatCandidate, error)

	// ListPendingMergeFunc mocks the ListPendingMerge method.
	ListPendingMergeFunc func(ctx context.Context, limit int) ([]domain.Beat, error)

	// SaveCanonicalFunc mocks the SaveCanonical method.
	SaveCanonicalFunc func(ctx context.Context, beatID int64, c domain.BeatCanonical) error

	// calls tracks calls to the methods.
	calls struct {
		// AppendTitleRevision holds details about calls to the AppendTitleRevision method.
		AppendTitleRevision []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
			// Title is the title argument value.
			Title string
			// Summary is the summary argument value.
			Summary string
		}
		// AttachOrSeed holds details about calls to the AttachOrSeed method.
		AttachOrSeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item domain.BeatCandidate
			// Threshold is the threshold argument value.
			Threshold float64
			// Window is the window argument value.
			Window time.Duration
			// MaxMembers is the maxMembers argument value.
			MaxMembers int
		}
		// GetUnbeatItems holds details about calls to the GetUnbeatItems method.
		GetUnbeatItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// ListPendingMerge holds details about calls to the ListPendingMerge method.
		ListPendingMerge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// SaveCanonical holds details about calls to the SaveCanonical method.
		SaveCanonical []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
			// C is the c argument value.
			C domain.BeatCanonical
		}
	}
	lockAppendTitleRevision sync.RWMutex
	lockAttachOrSeed        sync.RWMutex
	lockGetUnbeatItems      sync.RWMutex
	lockListPendingMerge    sync.RWMutex
	lockSaveCanonical       sync.RWMutex
}

// AppendTitleRevision calls AppendTitleRevisionFunc.
func (mock *BeatStoreMock) AppendTitleRevision(ctx context.Context, beatID int64, title string, summary string) error {
	if mock.AppendTitleRevisionFunc == nil {
		panic("BeatStoreMock.AppendTitleRevisionFunc: method is nil but BeatStore.AppendTitleRevision was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		BeatID  int64
		Title   string
		Summary string
	}{
		Ctx:     ctx,
		BeatID:  beatID,
		Title:   title,
		Summary: summary,
	}
	mock.lockAppendTitleRevision.Lock()
	mock.calls.AppendTitleRevision = append(mock.calls.AppendTitleRevision, callInfo)
	mock.lockAppendTitleRevision.Unlock()
	return mock.AppendTitleRevisionFunc(ctx, beatID, title, summary)
}

// AppendTitleRevisionCalls gets all the calls that were made to AppendTitleRevision.
// Check the length with:
//
//	len(mockedBeatStore.AppendTitleRevisionCalls())
func (mock *BeatStoreMock) AppendTitleRevisionCalls() []struct {
	Ctx     context.Context
	BeatID  int64
	Title   string
	Summary string
} {
	var calls []struct {
		Ctx     context.Context
		BeatID  int64
		Title   string
		Summary string
	}
	mock.lockAppendTitleRevision.RLock()
	calls = mock.calls.AppendTitleRevision
	mock.lockAppendTitleRevision.RUnlock()
	return calls
}

// AttachOrSeed calls AttachOrSeedFunc.
func (mock *BeatStoreMock) AttachOrSeed(ctx context.Context, item domain.BeatCandidate, threshold float64, window time.Duration, maxMembers int) (int64, bool, error) {
	if mock.AttachOrSeedFunc == nil {
		panic("BeatStoreMock.AttachOrSeedFunc: method is nil but BeatStore.AttachOrSeed was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Item       domain.BeatCandidate
		Threshold  float64
		Window     time.Duration
		MaxMembers int
	}{
		Ctx:        ctx,
		Item:       item,
		Threshold:  threshold,
		Window:     window,
		MaxMembers: maxMembers,
	}
	mock.lockAttachOrSeed.Lock()
	mock.calls.AttachOrSeed = append(mock.calls.AttachOrSeed, callInfo)
	mock.lockAttachOrSeed.Unlock()
	return mock.AttachOrSeedFunc(ctx, item, threshold, window, maxMembers)
}

// AttachOrSeedCalls gets all the calls that were made to AttachOrSeed.
// Check the length with:
//
//	len(mockedBeatStore.AttachOrSeedCalls())
func (mock *BeatStoreMock) AttachOrSeedCalls() []struct {
	Ctx        context.Context
	Item       domain.BeatCandidate
	Threshold  float64
	Window     time.Duration
	MaxMembers int
} {
	var calls []struct {
		Ctx        context.Context
		Item       domain.BeatCandidate
		Threshold  float64
		Window     time.Duration
		MaxMembers int
	}
	mock.lockAttachOrSeed.RLock()
	calls = mock.calls.AttachOrSeed
	mock.lockAttachOrSeed.RUnlock()
	return calls
}

// GetUnbeatItems calls GetUnbeatItemsFunc.
func (mock *BeatStoreMock) GetUnbeatItems(ctx context.Context, limit int) ([]domain.BeatCandidate, error) {
	if mock.GetUnbeatItemsFunc == nil {
		panic("BeatStoreMock.GetUnbeatItemsFunc: method is nil but BeatStore.GetUnbeatItems was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetUnbeatItems.Lock()
	mock.calls.GetUnbeatItems = append(mock.calls.GetUnbeatItems, callInfo)
	mock.lockGetUnbeatItems.Unlock()
	return mock.GetUnbeatItemsFunc(ctx, limit)
}

// GetUnbeatItemsCalls gets all the calls that were made to GetUnbeatItems.
// Check the length with:
//
//	len(mockedBeatStore.GetUnbeatItemsCalls())
func (mock *BeatStoreMock) GetUnbeatItemsCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockGetUnbeatItems.RLock()
	calls = mock.calls.GetUnbeatItems
	mock.lockGetUnbeatItems.RUnlock()
	return calls
}

// ListPendingMerge calls ListPendingMergeFunc.
func (mock *BeatStoreMock) ListPendingMerge(ctx context.Context, limit int) ([]domain.Beat, error) {
	if mock.ListPendingMergeFunc == nil {
		panic("BeatStoreMock.ListPendingMergeFunc: method is nil but BeatStore.ListPendingMerge was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockListPendingMerge.Lock()
	mock.calls.ListPendingMerge = append(mock.calls.ListPendingMerge, callInfo)
	mock.lockListPendingMerge.Unlock()
	return mock.ListPendingMergeFunc(ctx, limit)
}

// ListPendingMergeCalls gets all the calls that were made to ListPendingMerge.
// Check the length with:
//
//	len(mockedBeatStore.ListPendingMergeCalls())
func (mock *BeatStoreMock) ListPendingMergeCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockListPendingMerge.RLock()
	calls = mock.calls.ListPendingMerge
	mock.lockListPendingMerge.RUnlock()
	return calls
}

// SaveCanonical calls SaveCanonicalFunc.
func (mock *BeatStoreMock) SaveCanonical(ctx context.Context, beatID int64, c domain.BeatCanonical) error {
	if mock.SaveCanonicalFunc == nil {
		panic("BeatStoreMock.SaveCanonicalFunc: method is nil but BeatStore.SaveCanonical was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
		C      domain.BeatCanonical
	}{
		Ctx:    ctx,
		BeatID: beatID,
		C:      c,
	}
	mock.lockSaveCanonical.Lock()
	mock.calls.SaveCanonical = append(mock.calls.SaveCanonical, callInfo)
	mock.lockSaveCanonical.Unlock()
	return mock.SaveCanonicalFunc(ctx, beatID, c)
}

// SaveCanonicalCalls gets all the calls that were made to SaveCanonical.
// Check the length with:
//
//	len(mockedBeatStore.SaveCanonicalCalls())
func (mock *BeatStoreMock) SaveCanonicalCalls() []struct {
	Ctx    context.Context
	BeatID int64
	C      domain.BeatCanonical
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
		C      domain.BeatCanonical
	}
	mock.lockSaveCanonical.RLock()
	calls = mock.calls.SaveCanonical
	mock.lockSaveCanonical.RUnlock()
	return calls
}
