// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
	"github.com/umputun/newscope/pkg/llm"
)

// ClassifierMock is a mock implementation of scheduler.Classifier.
//
//	func TestSomethingThatUsesClassifier(t *testing.T) {
//
//		// make and configure a mocked scheduler.Classifier
//		mockedClassifier := &ClassifierMock{
//			GeneratePreferenceSummaryFunc: func(ctx context.Context, feedback []domain.FeedbackExample) (string, error) {
//				panic("mock out the GeneratePreferenceSummary method")
//			},
//			ScoreArticlesFunc: func(ctx context.Context, req llm.ClassifyRequest) ([]domain.Classification, error) {
//				panic("mock out the ScoreArticles method")
//			},
//			SummarizeArticleFunc: func(ctx context.Context, article domain.Item, req llm.ClassifyRequest) (domain.Classification, error) {
//				panic("mock out the SummarizeArticle method")
//			},
//			UpdatePreferenceSummaryFunc: func(ctx context.Context, currentSummary string, newFeedback []domain.FeedbackExample) (string, error) {
//				panic("mock out the UpdatePreferenceSummary method")
//			},
//		}
//
//		// use mockedClassifier in code that requires scheduler.Classifier
//		// and then make assertions.
//
//	}
type ClassifierMock struct {
	// GeneratePreferenceSummaryFunc mocks the GeneratePreferenceSummary method.
	GeneratePreferenceSummaryFunc func(ctx context.Context, feedback []domain.FeedbackExample) (string, error)

	// ScoreArticlesFunc mocks the ScoreArticles method.
	ScoreArticlesFunc func(ctx context.Context, req llm.ClassifyRequest) ([]domain.Classification, error)

	// SummarizeArticleFunc mocks the SummarizeArticle method.
	SummarizeArticleFunc func(ctx context.Context, article domain.Item, req llm.ClassifyRequest) (domain.Classification, error)

	// UpdatePreferenceSummaryFunc mocks the UpdatePreferenceSummary method.
	UpdatePreferenceSummaryFunc func(ctx context.Context, currentSummary string, newFeedback []domain.FeedbackExample) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GeneratePreferenceSummary holds details about calls to the GeneratePreferenceSummary method.
		GeneratePreferenceSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feedback is the feedback argument value.
			Feedback []domain.FeedbackExample
		}
		// ScoreArticles holds details about calls to the ScoreArticles method.
		ScoreArticles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req llm.ClassifyRequest
		}
		// SummarizeArticle holds details about calls to the SummarizeArticle method.
		SummarizeArticle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Article is the article argument value.
			Article domain.Item
			// Req is the req argument value.
			Req llm.ClassifyRequest
		}
		// UpdatePreferenceSummary holds details about calls to the UpdatePreferenceSummary method.
		UpdatePreferenceSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CurrentSummary is the currentSummary argument value.
			CurrentSummary string
			// NewFeedback is the newFeedback argument value.
			NewFeedback []domain.FeedbackExample
		}
	}
	lockGeneratePreferenceSummary sync.RWMutex
	lockScoreArticles             sync.RWMutex
	lockSummarizeArticle          sync.RWMutex
	lockUpdatePreferenceSummary   sync.RWMutex
}

// GeneratePreferenceSummary calls GeneratePreferenceSummaryFunc.
func (mock *ClassifierMock) GeneratePreferenceSummary(ctx context.Context, feedback []domain.FeedbackExample) (string, error) {
	if mock.GeneratePreferenceSummaryFunc == nil {
		panic("ClassifierMock.GeneratePreferenceSummaryFunc: method is nil but Classifier.GeneratePreferenceSummary was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Feedback []domain.FeedbackExample
	}{
		Ctx:      ctx,
		Feedback: feedback,
	}
	mock.lockGeneratePreferenceSummary.Lock()
	mock.calls.GeneratePreferenceSummary = append(mock.calls.GeneratePreferenceSummary, callInfo)
	mock.lockGeneratePreferenceSummary.Unlock()
	return mock.GeneratePreferenceSummaryFunc(ctx, feedback)
}

// GeneratePreferenceSummaryCalls gets all the calls that were made to GeneratePreferenceSummary.
// Check the length with:
//
//	len(mockedClassifier.GeneratePreferenceSummaryCalls())
func (mock *ClassifierMock) GeneratePreferenceSummaryCalls() []struct {
	Ctx      context.Context
	Feedback []domain.FeedbackExample
} {
	var calls []struct {
		Ctx      context.Context
		Feedback []domain.FeedbackExample
	}
	mock.lockGeneratePreferenceSummary.RLock()
	calls = mock.calls.GeneratePreferenceSummary
	mock.lockGeneratePreferenceSummary.RUnlock()
	return calls
}

// ScoreArticles calls ScoreArticlesFunc.
func (mock *ClassifierMock) ScoreArticles(ctx context.Context, req llm.ClassifyRequest) ([]domain.Classification, error) {
	if mock.ScoreArticlesFunc == nil {
		panic("ClassifierMock.ScoreArticlesFunc: method is nil but Classifier.ScoreArticles was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req llm.ClassifyRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockScoreArticles.Lock()
	mock.calls.ScoreArticles = append(mock.calls.ScoreArticles, callInfo)
	mock.lockScoreArticles.Unlock()
	return mock.ScoreArticlesFunc(ctx, req)
}

// ScoreArticlesCalls gets all the calls that were made to ScoreArticles.
// Check the length with:
//
//	len(mockedClassifier.ScoreArticlesCalls())
func (mock *ClassifierMock) ScoreArticlesCalls() []struct {
	Ctx context.Context
	Req llm.ClassifyRequest
} {
	var calls []struct {
		Ctx context.Context
		Req llm.ClassifyRequest
	}
	mock.lockScoreArticles.RLock()
	calls = mock.calls.ScoreArticles
	mock.lockScoreArticles.RUnlock()
	return calls
}

// SummarizeArticle calls SummarizeArticleFunc.
func (mock *ClassifierMock) SummarizeArticle(ctx context.Context, article domain.Item, req llm.ClassifyRequest) (domain.Classification, error) {
	if mock.SummarizeArticleFunc == nil {
		panic("ClassifierMock.SummarizeArticleFunc: method is nil but Classifier.SummarizeArticle was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Article domain.Item
		Req     llm.ClassifyRequest
	}{
		Ctx:     ctx,
		Article: article,
		Req:     req,
	}
	mock.lockSummarizeArticle.Lock()
	mock.calls.SummarizeArticle = append(mock.calls.SummarizeArticle, callInfo)
	mock.lockSummarizeArticle.Unlock()
	return mock.SummarizeArticleFunc(ctx, article, req)
}

// SummarizeArticleCalls gets all the calls that were made to SummarizeArticle.
// Check the length with:
//
//	len(mockedClassifier.SummarizeArticleCalls())
func (mock *ClassifierMock) SummarizeArticleCalls() []struct {
	Ctx     context.Context
	Article domain.Item
	Req     llm.ClassifyRequest
} {
	var calls []struct {
		Ctx     context.Context
		Article domain.Item
		Req     llm.ClassifyRequest
	}
	mock.lockSummarizeArticle.RLock()
	calls = mock.calls.SummarizeArticle
	mock.lockSummarizeArticle.RUnlock()
	return calls
}

// UpdatePreferenceSummary calls UpdatePreferenceSummaryFunc.
func (mock *ClassifierMock) UpdatePreferenceSummary(ctx context.Context, currentSummary string, newFeedback []domain.FeedbackExample) (string, error) {
	if mock.UpdatePreferenceSummaryFunc == nil {
		panic("ClassifierMock.UpdatePreferenceSummaryFunc: method is nil but Classifier.UpdatePreferenceSummary was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CurrentSummary string
		NewFeedback    []domain.FeedbackExample
	}{
		Ctx:            ctx,
		CurrentSummary: currentSummary,
		NewFeedback:    newFeedback,
	}
	mock.lockUpdatePreferenceSummary.Lock()
	mock.calls.UpdatePreferenceSummary = append(mock.calls.UpdatePreferenceSummary, callInfo)
	mock.lockUpdatePreferenceSummary.Unlock()
	return mock.UpdatePreferenceSummaryFunc(ctx, currentSummary, newFeedback)
}

// UpdatePreferenceSummaryCalls gets all the calls that were made to UpdatePreferenceSummary.
// Check the length with:
//
//	len(mockedClassifier.UpdatePreferenceSummaryCalls())
func (mock *ClassifierMock) UpdatePreferenceSummaryCalls() []struct {
	Ctx            context.Context
	CurrentSummary string
	NewFeedback    []domain.FeedbackExample
} {
	var calls []struct {
		Ctx            context.Context
		CurrentSummary string
		NewFeedback    []domain.FeedbackExample
	}
	mock.lockUpdatePreferenceSummary.RLock()
	calls = mock.calls.UpdatePreferenceSummary
	mock.lockUpdatePreferenceSummary.RUnlock()
	return calls
}
