// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// EmbedStoreMock is a mock implementation of scheduler.EmbedStore.
//
//	func TestSomethingThatUsesEmbedStore(t *testing.T) {
//
//		// make and configure a mocked scheduler.EmbedStore
//		mockedEmbedStore := &EmbedStoreMock{
//			PutEmbeddingFunc: func(ctx context.Context, itemID int64, model string, v []float32) error {
//				panic("mock out the PutEmbedding method")
//			},
//		}
//
//		// use mockedEmbedStore in code that requires scheduler.EmbedStore
//		// and then make assertions.
//
//	}
type EmbedStoreMock struct {
	// PutEmbeddingFunc mocks the PutEmbedding method.
	PutEmbeddingFunc func(ctx context.Context, itemID int64, model string, v []float32) error

	// calls tracks calls to the methods.
	calls struct {
		// PutEmbedding holds details about calls to the PutEmbedding method.
		PutEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID int64
			// Model is the model argument value.
			Model string
			// V is the v argument value.
			V []float32
		}
	}
	lockPutEmbedding sync.RWMutex
}

// PutEmbedding calls PutEmbeddingFunc.
func (mock *EmbedStoreMock) PutEmbedding(ctx context.Context, itemID int64, model string, v []float32) error {
	if mock.PutEmbeddingFunc == nil {
		panic("EmbedStoreMock.PutEmbeddingFunc: method is nil but EmbedStore.PutEmbedding was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ItemID int64
		Model  string
		V      []float32
	}{
		Ctx:    ctx,
		ItemID: itemID,
		Model:  model,
		V:      v,
	}
	mock.lockPutEmbedding.Lock()
	mock.calls.PutEmbedding = append(mock.calls.PutEmbedding, callInfo)
	mock.lockPutEmbedding.Unlock()
	return mock.PutEmbeddingFunc(ctx, itemID, model, v)
}

// PutEmbeddingCalls gets all the calls that were made to PutEmbedding.
// Check the length with:
//
//	len(mockedEmbedStore.PutEmbeddingCalls())
func (mock *EmbedStoreMock) PutEmbeddingCalls() []struct {
	Ctx    context.Context
	ItemID int64
	Model  string
	V      []float32
} {
	var calls []struct {
		Ctx    context.Context
		ItemID int64
		Model  string
		V      []float32
	}
	mock.lockPutEmbedding.RLock()
	calls = mock.calls.PutEmbedding
	mock.lockPutEmbedding.RUnlock()
	return calls
}
