// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// EmbedderMock is a mock implementation of scheduler.Embedder.
//
//	func TestSomethingThatUsesEmbedder(t *testing.T) {
//
//		// make and configure a mocked scheduler.Embedder
//		mockedEmbedder := &EmbedderMock{
//			EmbedFunc: func(ctx context.Context, text string) ([]float32, error) {
//				panic("mock out the Embed method")
//			},
//		}
//
//		// use mockedEmbedder in code that requires scheduler.Embedder
//		// and then make assertions.
//
//	}
type EmbedderMock struct {
	// EmbedFunc mocks the Embed method.
	EmbedFunc func(ctx context.Context, text string) ([]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Embed holds details about calls to the Embed method.
		Embed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Text is the text argument value.
			Text string
		}
	}
	lockEmbed sync.RWMutex
}

// Embed calls EmbedFunc.
func (mock *EmbedderMock) Embed(ctx context.Context, text string) ([]float32, error) {
	if mock.EmbedFunc == nil {
		panic("EmbedderMock.EmbedFunc: method is nil but Embedder.Embed was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Text string
	}{
		Ctx:  ctx,
		Text: text,
	}
	mock.lockEmbed.Lock()
	mock.calls.Embed = append(mock.calls.Embed, callInfo)
	mock.lockEmbed.Unlock()
	return mock.EmbedFunc(ctx, text)
}

// EmbedCalls gets all the calls that were made to Embed.
// Check the length with:
//
//	len(mockedEmbedder.EmbedCalls())
func (mock *EmbedderMock) EmbedCalls() []struct {
	Ctx  context.Context
	Text string
} {
	var calls []struct {
		Ctx  context.Context
		Text string
	}
	mock.lockEmbed.RLock()
	calls = mock.calls.Embed
	mock.lockEmbed.RUnlock()
	return calls
}
