// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
)

// EntityExtractorMock is a mock implementation of scheduler.EntityExtractor.
//
//	func TestSomethingThatUsesEntityExtractor(t *testing.T) {
//
//		// make and configure a mocked scheduler.EntityExtractor
//		mockedEntityExtractor := &EntityExtractorMock{
//			ExtractFunc: func(ctx context.Context, items []domain.ClassifiedItem) ([][]string, error) {
//				panic("mock out the Extract method")
//			},
//		}
//
//		// use mockedEntityExtractor in code that requires scheduler.EntityExtractor
//		// and then make assertions.
//
//	}
type EntityExtractorMock struct {
	// ExtractFunc mocks the Extract method.
	ExtractFunc func(ctx context.Context, items []domain.ClassifiedItem) ([][]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Extract holds details about calls to the Extract method.
		Extract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Items is the items argument value.
			Items []domain.ClassifiedItem
		}
	}
	lockExtract sync.RWMutex
}

// Extract calls ExtractFunc.
func (mock *EntityExtractorMock) Extract(ctx context.Context, items []domain.ClassifiedItem) ([][]string, error) {
	if mock.ExtractFunc == nil {
		panic("EntityExtractorMock.ExtractFunc: method is nil but EntityExtractor.Extract was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Items []domain.ClassifiedItem
	}{
		Ctx:   ctx,
		Items: items,
	}
	mock.lockExtract.Lock()
	mock.calls.Extract = append(mock.calls.Extract, callInfo)
	mock.lockExtract.Unlock()
	return mock.ExtractFunc(ctx, items)
}

// ExtractCalls gets all the calls that were made to Extract.
// Check the length with:
//
//	len(mockedEntityExtractor.ExtractCalls())
func (mock *EntityExtractorMock) ExtractCalls() []struct {
	Ctx   context.Context
	Items []domain.ClassifiedItem
} {
	var calls []struct {
		Ctx   context.Context
		Items []domain.ClassifiedItem
	}
	mock.lockExtract.RLock()
	calls = mock.calls.Extract
	mock.lockExtract.RUnlock()
	return calls
}
