// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
)

// EntityStoreMock is a mock implementation of scheduler.EntityStore.
//
//	func TestSomethingThatUsesEntityStore(t *testing.T) {
//
//		// make and configure a mocked scheduler.EntityStore
//		mockedEntityStore := &EntityStoreMock{
//			BeatForItemFunc: func(ctx context.Context, itemID int64) (int64, bool, error) {
//				panic("mock out the BeatForItem method")
//			},
//			ListPendingEntitiesFunc: func(ctx context.Context, limit int) ([]domain.ClassifiedItem, error) {
//				panic("mock out the ListPendingEntities method")
//			},
//			SaveEntitiesFunc: func(ctx context.Context, itemID int64, entities []string) error {
//				panic("mock out the SaveEntities method")
//			},
//		}
//
//		// use mockedEntityStore in code that requires scheduler.EntityStore
//		// and then make assertions.
//
//	}
type EntityStoreMock struct {
	// BeatForItemFunc mocks the BeatForItem method.
	BeatForItemFunc func(ctx context.Context, itemID int64) (int64, bool, error)

	// ListPendingEntitiesFunc mocks the ListPendingEntities method.
	ListPendingEntitiesFunc func(ctx context.Context, limit int) ([]domain.ClassifiedItem, error)

	// SaveEntitiesFunc mocks the SaveEntities method.
	SaveEntitiesFunc func(ctx context.Context, itemID int64, entities []string) error

	// calls tracks calls to the methods.
	calls struct {
		// BeatForItem holds details about calls to the BeatForItem method.
		BeatForItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID int64
		}
		// ListPendingEntities holds details about calls to the ListPendingEntities method.
		ListPendingEntities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// SaveEntities holds details about calls to the SaveEntities method.
		SaveEntities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID int64
			// Entities is the entities argument value.
			Entities []string
		}
	}
	lockBeatForItem         sync.RWMutex
	lockListPendingEntities sync.RWMutex
	lockSaveEntities        sync.RWMutex
}

// BeatForItem calls BeatForItemFunc.
func (mock *EntityStoreMock) BeatForItem(ctx context.Context, itemID int64) (int64, bool, error) {
	if mock.BeatForItemFunc == nil {
		panic("EntityStoreMock.BeatForItemFunc: method is nil but EntityStore.BeatForItem was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ItemID int64
	}{
		Ctx:    ctx,
		ItemID: itemID,
	}
	mock.lockBeatForItem.Lock()
	mock.calls.BeatForItem = append(mock.calls.BeatForItem, callInfo)
	mock.lockBeatForItem.Unlock()
	return mock.BeatForItemFunc(ctx, itemID)
}

// BeatForItemCalls gets all the calls that were made to BeatForItem.
// Check the length with:
//
//	len(mockedEntityStore.BeatForItemCalls())
func (mock *EntityStoreMock) BeatForItemCalls() []struct {
	Ctx    context.Context
	ItemID int64
} {
	var calls []struct {
		Ctx    context.Context
		ItemID int64
	}
	mock.lockBeatForItem.RLock()
	calls = mock.calls.BeatForItem
	mock.lockBeatForItem.RUnlock()
	return calls
}

// ListPendingEntities calls ListPendingEntitiesFunc.
func (mock *EntityStoreMock) ListPendingEntities(ctx context.Context, limit int) ([]domain.ClassifiedItem, error) {
	if mock.ListPendingEntitiesFunc == nil {
		panic("EntityStoreMock.ListPendingEntitiesFunc: method is nil but EntityStore.ListPendingEntities was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockListPendingEntities.Lock()
	mock.calls.ListPendingEntities = append(mock.calls.ListPendingEntities, callInfo)
	mock.lockListPendingEntities.Unlock()
	return mock.ListPendingEntitiesFunc(ctx, limit)
}

// ListPendingEntitiesCalls gets all the calls that were made to ListPendingEntities.
// Check the length with:
//
//	len(mockedEntityStore.ListPendingEntitiesCalls())
func (mock *EntityStoreMock) ListPendingEntitiesCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockListPendingEntities.RLock()
	calls = mock.calls.ListPendingEntities
	mock.lockListPendingEntities.RUnlock()
	return calls
}

// SaveEntities calls SaveEntitiesFunc.
func (mock *EntityStoreMock) SaveEntities(ctx context.Context, itemID int64, entities []string) error {
	if mock.SaveEntitiesFunc == nil {
		panic("EntityStoreMock.SaveEntitiesFunc: method is nil but EntityStore.SaveEntities was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ItemID   int64
		Entities []string
	}{
		Ctx:      ctx,
		ItemID:   itemID,
		Entities: entities,
	}
	mock.lockSaveEntities.Lock()
	mock.calls.SaveEntities = append(mock.calls.SaveEntities, callInfo)
	mock.lockSaveEntities.Unlock()
	return mock.SaveEntitiesFunc(ctx, itemID, entities)
}

// SaveEntitiesCalls gets all the calls that were made to SaveEntities.
// Check the length with:
//
//	len(mockedEntityStore.SaveEntitiesCalls())
func (mock *EntityStoreMock) SaveEntitiesCalls() []struct {
	Ctx      context.Context
	ItemID   int64
	Entities []string
} {
	var calls []struct {
		Ctx      context.Context
		ItemID   int64
		Entities []string
	}
	mock.lockSaveEntities.RLock()
	calls = mock.calls.SaveEntities
	mock.lockSaveEntities.RUnlock()
	return calls
}
