// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// GroupingAssignerMock is a mock implementation of scheduler.GroupingAssigner.
//
//	func TestSomethingThatUsesGroupingAssigner(t *testing.T) {
//
//		// make and configure a mocked scheduler.GroupingAssigner
//		mockedGroupingAssigner := &GroupingAssignerMock{
//			ReassignFunc: func(ctx context.Context, beatID int64) error {
//				panic("mock out the Reassign method")
//			},
//		}
//
//		// use mockedGroupingAssigner in code that requires scheduler.GroupingAssigner
//		// and then make assertions.
//
//	}
type GroupingAssignerMock struct {
	// ReassignFunc mocks the Reassign method.
	ReassignFunc func(ctx context.Context, beatID int64) error

	// calls tracks calls to the methods.
	calls struct {
		// Reassign holds details about calls to the Reassign method.
		Reassign []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
	}
	lockReassign sync.RWMutex
}

// Reassign calls ReassignFunc.
func (mock *GroupingAssignerMock) Reassign(ctx context.Context, beatID int64) error {
	if mock.ReassignFunc == nil {
		panic("GroupingAssignerMock.ReassignFunc: method is nil but GroupingAssigner.Reassign was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockReassign.Lock()
	mock.calls.Reassign = append(mock.calls.Reassign, callInfo)
	mock.lockReassign.Unlock()
	return mock.ReassignFunc(ctx, beatID)
}

// ReassignCalls gets all the calls that were made to Reassign.
// Check the length with:
//
//	len(mockedGroupingAssigner.ReassignCalls())
func (mock *GroupingAssignerMock) ReassignCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockReassign.RLock()
	calls = mock.calls.Reassign
	mock.lockReassign.RUnlock()
	return calls
}
