// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
)

// MergerMock is a mock implementation of scheduler.Merger.
//
//	func TestSomethingThatUsesMerger(t *testing.T) {
//
//		// make and configure a mocked scheduler.Merger
//		mockedMerger := &MergerMock{
//			MergeFunc: func(ctx context.Context, members []domain.ClassifiedItem) (domain.BeatCanonical, error) {
//				panic("mock out the Merge method")
//			},
//		}
//
//		// use mockedMerger in code that requires scheduler.Merger
//		// and then make assertions.
//
//	}
type MergerMock struct {
	// MergeFunc mocks the Merge method.
	MergeFunc func(ctx context.Context, members []domain.ClassifiedItem) (domain.BeatCanonical, error)

	// calls tracks calls to the methods.
	calls struct {
		// Merge holds details about calls to the Merge method.
		Merge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Members is the members argument value.
			Members []domain.ClassifiedItem
		}
	}
	lockMerge sync.RWMutex
}

// Merge calls MergeFunc.
func (mock *MergerMock) Merge(ctx context.Context, members []domain.ClassifiedItem) (domain.BeatCanonical, error) {
	if mock.MergeFunc == nil {
		panic("MergerMock.MergeFunc: method is nil but Merger.Merge was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Members []domain.ClassifiedItem
	}{
		Ctx:     ctx,
		Members: members,
	}
	mock.lockMerge.Lock()
	mock.calls.Merge = append(mock.calls.Merge, callInfo)
	mock.lockMerge.Unlock()
	return mock.MergeFunc(ctx, members)
}

// MergeCalls gets all the calls that were made to Merge.
// Check the length with:
//
//	len(mockedMerger.MergeCalls())
func (mock *MergerMock) MergeCalls() []struct {
	Ctx     context.Context
	Members []domain.ClassifiedItem
} {
	var calls []struct {
		Ctx     context.Context
		Members []domain.ClassifiedItem
	}
	mock.lockMerge.RLock()
	calls = mock.calls.Merge
	mock.lockMerge.RUnlock()
	return calls
}
