// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
)

// BeatRepoMock is a mock implementation of server.BeatRepo.
//
//	func TestSomethingThatUsesBeatRepo(t *testing.T) {
//
//		// make and configure a mocked server.BeatRepo
//		mockedBeatRepo := &BeatRepoMock{
//			GetBeatFunc: func(ctx context.Context, beatID int64) (domain.BeatWithMembers, error) {
//				panic("mock out the GetBeat method")
//			},
//			ListBeatsFunc: func(ctx context.Context, limit int, offset int) ([]domain.BeatWithMembers, error) {
//				panic("mock out the ListBeats method")
//			},
//			MarkViewedFunc: func(ctx context.Context, beatID int64) error {
//				panic("mock out the MarkViewed method")
//			},
//			SearchFunc: func(ctx context.Context, query string, limit int, offset int) ([]domain.BeatWithMembers, error) {
//				panic("mock out the Search method")
//			},
//			SetFeedbackFunc: func(ctx context.Context, beatID int64, feedback string) error {
//				panic("mock out the SetFeedback method")
//			},
//		}
//
//		// use mockedBeatRepo in code that requires server.BeatRepo
//		// and then make assertions.
//
//	}
type BeatRepoMock struct {
	// GetBeatFunc mocks the GetBeat method.
	GetBeatFunc func(ctx context.Context, beatID int64) (domain.BeatWithMembers, error)

	// ListBeatsFunc mocks the ListBeats method.
	ListBeatsFunc func(ctx context.Context, limit int, offset int) ([]domain.BeatWithMembers, error)

	// MarkViewedFunc mocks the MarkViewed method.
	MarkViewedFunc func(ctx context.Context, beatID int64) error

	// SearchFunc mocks the Search method.
	SearchFunc func(ctx context.Context, query string, limit int, offset int) ([]domain.BeatWithMembers, error)

	// SetFeedbackFunc mocks the SetFeedback method.
	SetFeedbackFunc func(ctx context.Context, beatID int64, feedback string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetBeat holds details about calls to the GetBeat method.
		GetBeat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
		// ListBeats holds details about calls to the ListBeats method.
		ListBeats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// MarkViewed holds details about calls to the MarkViewed method.
		MarkViewed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
		// Search holds details about calls to the Search method.
		Search []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// SetFeedback holds details about calls to the SetFeedback method.
		SetFeedback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
			// Feedback is the feedback argument value.
			Feedback string
		}
	}
	lockGetBeat     sync.RWMutex
	lockListBeats   sync.RWMutex
	lockMarkViewed  sync.RWMutex
	lockSearch      sync.RWMutex
	lockSetFeedback sync.RWMutex
}

// GetBeat calls GetBeatFunc.
func (mock *BeatRepoMock) GetBeat(ctx context.Context, beatID int64) (domain.BeatWithMembers, error) {
	if mock.GetBeatFunc == nil {
		panic("BeatRepoMock.GetBeatFunc: method is nil but BeatRepo.GetBeat was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockGetBeat.Lock()
	mock.calls.GetBeat = append(mock.calls.GetBeat, callInfo)
	mock.lockGetBeat.Unlock()
	return mock.GetBeatFunc(ctx, beatID)
}

// GetBeatCalls gets all the calls that were made to GetBeat.
// Check the length with:
//
//	len(mockedBeatRepo.GetBeatCalls())
func (mock *BeatRepoMock) GetBeatCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockGetBeat.RLock()
	calls = mock.calls.GetBeat
	mock.lockGetBeat.RUnlock()
	return calls
}

// ListBeats calls ListBeatsFunc.
func (mock *BeatRepoMock) ListBeats(ctx context.Context, limit int, offset int) ([]domain.BeatWithMembers, error) {
	if mock.ListBeatsFunc == nil {
		panic("BeatRepoMock.ListBeatsFunc: method is nil but BeatRepo.ListBeats was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListBeats.Lock()
	mock.calls.ListBeats = append(mock.calls.ListBeats, callInfo)
	mock.lockListBeats.Unlock()
	return mock.ListBeatsFunc(ctx, limit, offset)
}

// ListBeatsCalls gets all the calls that were made to ListBeats.
// Check the length with:
//
//	len(mockedBeatRepo.ListBeatsCalls())
func (mock *BeatRepoMock) ListBeatsCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockListBeats.RLock()
	calls = mock.calls.ListBeats
	mock.lockListBeats.RUnlock()
	return calls
}

// MarkViewed calls MarkViewedFunc.
func (mock *BeatRepoMock) MarkViewed(ctx context.Context, beatID int64) error {
	if mock.MarkViewedFunc == nil {
		panic("BeatRepoMock.MarkViewedFunc: method is nil but BeatRepo.MarkViewed was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockMarkViewed.Lock()
	mock.calls.MarkViewed = append(mock.calls.MarkViewed, callInfo)
	mock.lockMarkViewed.Unlock()
	return mock.MarkViewedFunc(ctx, beatID)
}

// MarkViewedCalls gets all the calls that were made to MarkViewed.
// Check the length with:
//
//	len(mockedBeatRepo.MarkViewedCalls())
func (mock *BeatRepoMock) MarkViewedCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockMarkViewed.RLock()
	calls = mock.calls.MarkViewed
	mock.lockMarkViewed.RUnlock()
	return calls
}

// Search calls SearchFunc.
func (mock *BeatRepoMock) Search(ctx context.Context, query string, limit int, offset int) ([]domain.BeatWithMembers, error) {
	if mock.SearchFunc == nil {
		panic("BeatRepoMock.SearchFunc: method is nil but BeatRepo.Search was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Query  string
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Query:  query,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockSearch.Lock()
	mock.calls.Search = append(mock.calls.Search, callInfo)
	mock.lockSearch.Unlock()
	return mock.SearchFunc(ctx, query, limit, offset)
}

// SearchCalls gets all the calls that were made to Search.
// Check the length with:
//
//	len(mockedBeatRepo.SearchCalls())
func (mock *BeatRepoMock) SearchCalls() []struct {
	Ctx    context.Context
	Query  string
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Query  string
		Limit  int
		Offset int
	}
	mock.lockSearch.RLock()
	calls = mock.calls.Search
	mock.lockSearch.RUnlock()
	return calls
}

// SetFeedback calls SetFeedbackFunc.
func (mock *BeatRepoMock) SetFeedback(ctx context.Context, beatID int64, feedback string) error {
	if mock.SetFeedbackFunc == nil {
		panic("BeatRepoMock.SetFeedbackFunc: method is nil but BeatRepo.SetFeedback was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BeatID   int64
		Feedback string
	}{
		Ctx:      ctx,
		BeatID:   beatID,
		Feedback: feedback,
	}
	mock.lockSetFeedback.Lock()
	mock.calls.SetFeedback = append(mock.calls.SetFeedback, callInfo)
	mock.lockSetFeedback.Unlock()
	return mock.SetFeedbackFunc(ctx, beatID, feedback)
}

// SetFeedbackCalls gets all the calls that were made to SetFeedback.
// Check the length with:
//
//	len(mockedBeatRepo.SetFeedbackCalls())
func (mock *BeatRepoMock) SetFeedbackCalls() []struct {
	Ctx      context.Context
	BeatID   int64
	Feedback string
} {
	var calls []struct {
		Ctx      context.Context
		BeatID   int64
		Feedback string
	}
	mock.lockSetFeedback.RLock()
	calls = mock.calls.SetFeedback
	mock.lockSetFeedback.RUnlock()
	return calls
}
