// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/umputun/newscope/pkg/domain"
	"github.com/umputun/newscope/pkg/repository"
)

// DatabaseMock is a mock implementation of server.Database.
//
//	func TestSomethingThatUsesDatabase(t *testing.T) {
//
//		// make and configure a mocked server.Database
//		mockedDatabase := &DatabaseMock{
//			CreateFeedFunc: func(ctx context.Context, feed *domain.Feed) error {
//				panic("mock out the CreateFeed method")
//			},
//			CreateGroupingFunc: func(ctx context.Context, g domain.Grouping) (int64, error) {
//				panic("mock out the CreateGrouping method")
//			},
//			DeleteFeedFunc: func(ctx context.Context, feedID int64) error {
//				panic("mock out the DeleteFeed method")
//			},
//			DeleteGroupingFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteGrouping method")
//			},
//			GetActiveFeedNamesFunc: func(ctx context.Context, minScore float64) ([]string, error) {
//				panic("mock out the GetActiveFeedNames method")
//			},
//			GetAllFeedsFunc: func(ctx context.Context) ([]domain.Feed, error) {
//				panic("mock out the GetAllFeeds method")
//			},
//			GetBeatFunc: func(ctx context.Context, beatID int64) (domain.BeatWithMembers, error) {
//				panic("mock out the GetBeat method")
//			},
//			GetBigTagsFunc: func(ctx context.Context, threshold int) (map[string]int, error) {
//				panic("mock out the GetBigTags method")
//			},
//			GetClassifiedItemFunc: func(ctx context.Context, itemID int64) (*domain.ClassifiedItem, error) {
//				panic("mock out the GetClassifiedItem method")
//			},
//			GetClassifiedItemsFunc: func(ctx context.Context, minScore float64, topic string, limit int) ([]domain.ClassifiedItem, error) {
//				panic("mock out the GetClassifiedItems method")
//			},
//			GetClassifiedItemsCountFunc: func(ctx context.Context, req domain.ArticlesRequest) (int, error) {
//				panic("mock out the GetClassifiedItemsCount method")
//			},
//			GetClassifiedItemsWithFiltersFunc: func(ctx context.Context, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error) {
//				panic("mock out the GetClassifiedItemsWithFilters method")
//			},
//			GetFeedByNameFunc: func(ctx context.Context, name string) (*domain.Feed, error) {
//				panic("mock out the GetFeedByName method")
//			},
//			GetFeedsFunc: func(ctx context.Context) ([]domain.Feed, error) {
//				panic("mock out the GetFeeds method")
//			},
//			GetGroupingFunc: func(ctx context.Context, id int64) (domain.Grouping, error) {
//				panic("mock out the GetGrouping method")
//			},
//			GetGroupingBySlugFunc: func(ctx context.Context, slug string) (domain.Grouping, error) {
//				panic("mock out the GetGroupingBySlug method")
//			},
//			GetItemsFunc: func(ctx context.Context, limit int, offset int) ([]domain.Item, error) {
//				panic("mock out the GetItems method")
//			},
//			GetSearchItemsCountFunc: func(ctx context.Context, searchQuery string, req domain.ArticlesRequest) (int, error) {
//				panic("mock out the GetSearchItemsCount method")
//			},
//			GetSettingFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the GetSetting method")
//			},
//			GetTopTopicsByScoreFunc: func(ctx context.Context, minScore float64, limit int) ([]domain.TopicWithScore, error) {
//				panic("mock out the GetTopTopicsByScore method")
//			},
//			GetTopicsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetTopics method")
//			},
//			GetTopicsFilteredFunc: func(ctx context.Context, minScore float64) ([]string, error) {
//				panic("mock out the GetTopicsFiltered method")
//			},
//			GroupingCountsFunc: func(ctx context.Context) (map[int64]int, error) {
//				panic("mock out the GroupingCounts method")
//			},
//			ListBeatsFunc: func(ctx context.Context, opts repository.ListBeatsOptions) ([]domain.BeatWithMembers, error) {
//				panic("mock out the ListBeats method")
//			},
//			ListGroupingsFunc: func(ctx context.Context) ([]domain.Grouping, error) {
//				panic("mock out the ListGroupings method")
//			},
//			ListTitleRevisionsFunc: func(ctx context.Context, beatID int64) ([]domain.TitleRevision, error) {
//				panic("mock out the ListTitleRevisions method")
//			},
//			MarkViewedFunc: func(ctx context.Context, beatID int64) error {
//				panic("mock out the MarkViewed method")
//			},
//			ReorderGroupingsFunc: func(ctx context.Context, idsInOrder []int64) error {
//				panic("mock out the ReorderGroupings method")
//			},
//			SearchBeatsWithMembersFunc: func(ctx context.Context, query string, limit int) ([]domain.BeatWithMembers, error) {
//				panic("mock out the SearchBeatsWithMembers method")
//			},
//			SearchItemsFunc: func(ctx context.Context, searchQuery string, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error) {
//				panic("mock out the SearchItems method")
//			},
//			SetFeedbackFunc: func(ctx context.Context, beatID int64, feedback string) error {
//				panic("mock out the SetFeedback method")
//			},
//			SetSettingFunc: func(ctx context.Context, key string, value string) error {
//				panic("mock out the SetSetting method")
//			},
//			SuggestTagsFunc: func(ctx context.Context, prefix string, limit int) ([]string, error) {
//				panic("mock out the SuggestTags method")
//			},
//			UpdateFeedFunc: func(ctx context.Context, feedID int64, title string, feedURL string, iconURL string, fetchInterval time.Duration) error {
//				panic("mock out the UpdateFeed method")
//			},
//			UpdateFeedStatusFunc: func(ctx context.Context, feedID int64, enabled bool) error {
//				panic("mock out the UpdateFeedStatus method")
//			},
//			UpdateGroupingFunc: func(ctx context.Context, g domain.Grouping) error {
//				panic("mock out the UpdateGrouping method")
//			},
//			UpdateItemFeedbackFunc: func(ctx context.Context, itemID int64, feedback string) error {
//				panic("mock out the UpdateItemFeedback method")
//			},
//		}
//
//		// use mockedDatabase in code that requires server.Database
//		// and then make assertions.
//
//	}
type DatabaseMock struct {
	// CreateFeedFunc mocks the CreateFeed method.
	CreateFeedFunc func(ctx context.Context, feed *domain.Feed) error

	// CreateGroupingFunc mocks the CreateGrouping method.
	CreateGroupingFunc func(ctx context.Context, g domain.Grouping) (int64, error)

	// DeleteFeedFunc mocks the DeleteFeed method.
	DeleteFeedFunc func(ctx context.Context, feedID int64) error

	// DeleteGroupingFunc mocks the DeleteGrouping method.
	DeleteGroupingFunc func(ctx context.Context, id int64) error

	// GetActiveFeedNamesFunc mocks the GetActiveFeedNames method.
	GetActiveFeedNamesFunc func(ctx context.Context, minScore float64) ([]string, error)

	// GetAllFeedsFunc mocks the GetAllFeeds method.
	GetAllFeedsFunc func(ctx context.Context) ([]domain.Feed, error)

	// GetBeatFunc mocks the GetBeat method.
	GetBeatFunc func(ctx context.Context, beatID int64) (domain.BeatWithMembers, error)

	// GetBigTagsFunc mocks the GetBigTags method.
	GetBigTagsFunc func(ctx context.Context, threshold int) (map[string]int, error)

	// GetClassifiedItemFunc mocks the GetClassifiedItem method.
	GetClassifiedItemFunc func(ctx context.Context, itemID int64) (*domain.ClassifiedItem, error)

	// GetClassifiedItemsFunc mocks the GetClassifiedItems method.
	GetClassifiedItemsFunc func(ctx context.Context, minScore float64, topic string, limit int) ([]domain.ClassifiedItem, error)

	// GetClassifiedItemsCountFunc mocks the GetClassifiedItemsCount method.
	GetClassifiedItemsCountFunc func(ctx context.Context, req domain.ArticlesRequest) (int, error)

	// GetClassifiedItemsWithFiltersFunc mocks the GetClassifiedItemsWithFilters method.
	GetClassifiedItemsWithFiltersFunc func(ctx context.Context, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error)

	// GetFeedByNameFunc mocks the GetFeedByName method.
	GetFeedByNameFunc func(ctx context.Context, name string) (*domain.Feed, error)

	// GetFeedsFunc mocks the GetFeeds method.
	GetFeedsFunc func(ctx context.Context) ([]domain.Feed, error)

	// GetGroupingFunc mocks the GetGrouping method.
	GetGroupingFunc func(ctx context.Context, id int64) (domain.Grouping, error)

	// GetGroupingBySlugFunc mocks the GetGroupingBySlug method.
	GetGroupingBySlugFunc func(ctx context.Context, slug string) (domain.Grouping, error)

	// GetItemsFunc mocks the GetItems method.
	GetItemsFunc func(ctx context.Context, limit int, offset int) ([]domain.Item, error)

	// GetSearchItemsCountFunc mocks the GetSearchItemsCount method.
	GetSearchItemsCountFunc func(ctx context.Context, searchQuery string, req domain.ArticlesRequest) (int, error)

	// GetSettingFunc mocks the GetSetting method.
	GetSettingFunc func(ctx context.Context, key string) (string, error)

	// GetTopTopicsByScoreFunc mocks the GetTopTopicsByScore method.
	GetTopTopicsByScoreFunc func(ctx context.Context, minScore float64, limit int) ([]domain.TopicWithScore, error)

	// GetTopicsFunc mocks the GetTopics method.
	GetTopicsFunc func(ctx context.Context) ([]string, error)

	// GetTopicsFilteredFunc mocks the GetTopicsFiltered method.
	GetTopicsFilteredFunc func(ctx context.Context, minScore float64) ([]string, error)

	// GroupingCountsFunc mocks the GroupingCounts method.
	GroupingCountsFunc func(ctx context.Context) (map[int64]int, error)

	// ListBeatsFunc mocks the ListBeats method.
	ListBeatsFunc func(ctx context.Context, opts repository.ListBeatsOptions) ([]domain.BeatWithMembers, error)

	// ListGroupingsFunc mocks the ListGroupings method.
	ListGroupingsFunc func(ctx context.Context) ([]domain.Grouping, error)

	// ListTitleRevisionsFunc mocks the ListTitleRevisions method.
	ListTitleRevisionsFunc func(ctx context.Context, beatID int64) ([]domain.TitleRevision, error)

	// MarkViewedFunc mocks the MarkViewed method.
	MarkViewedFunc func(ctx context.Context, beatID int64) error

	// ReorderGroupingsFunc mocks the ReorderGroupings method.
	ReorderGroupingsFunc func(ctx context.Context, idsInOrder []int64) error

	// SearchBeatsWithMembersFunc mocks the SearchBeatsWithMembers method.
	SearchBeatsWithMembersFunc func(ctx context.Context, query string, limit int) ([]domain.BeatWithMembers, error)

	// SearchItemsFunc mocks the SearchItems method.
	SearchItemsFunc func(ctx context.Context, searchQuery string, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error)

	// SetFeedbackFunc mocks the SetFeedback method.
	SetFeedbackFunc func(ctx context.Context, beatID int64, feedback string) error

	// SetSettingFunc mocks the SetSetting method.
	SetSettingFunc func(ctx context.Context, key string, value string) error

	// SuggestTagsFunc mocks the SuggestTags method.
	SuggestTagsFunc func(ctx context.Context, prefix string, limit int) ([]string, error)

	// UpdateFeedFunc mocks the UpdateFeed method.
	UpdateFeedFunc func(ctx context.Context, feedID int64, title string, feedURL string, iconURL string, fetchInterval time.Duration) error

	// UpdateFeedStatusFunc mocks the UpdateFeedStatus method.
	UpdateFeedStatusFunc func(ctx context.Context, feedID int64, enabled bool) error

	// UpdateGroupingFunc mocks the UpdateGrouping method.
	UpdateGroupingFunc func(ctx context.Context, g domain.Grouping) error

	// UpdateItemFeedbackFunc mocks the UpdateItemFeedback method.
	UpdateItemFeedbackFunc func(ctx context.Context, itemID int64, feedback string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateFeed holds details about calls to the CreateFeed method.
		CreateFeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Feed is the feed argument value.
			Feed *domain.Feed
		}
		// CreateGrouping holds details about calls to the CreateGrouping method.
		CreateGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// G is the g argument value.
			G domain.Grouping
		}
		// DeleteFeed holds details about calls to the DeleteFeed method.
		DeleteFeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FeedID is the feedID argument value.
			FeedID int64
		}
		// DeleteGrouping holds details about calls to the DeleteGrouping method.
		DeleteGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetActiveFeedNames holds details about calls to the GetActiveFeedNames method.
		GetActiveFeedNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MinScore is the minScore argument value.
			MinScore float64
		}
		// GetAllFeeds holds details about calls to the GetAllFeeds method.
		GetAllFeeds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetBeat holds details about calls to the GetBeat method.
		GetBeat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
		// GetBigTags holds details about calls to the GetBigTags method.
		GetBigTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threshold is the threshold argument value.
			Threshold int
		}
		// GetClassifiedItem holds details about calls to the GetClassifiedItem method.
		GetClassifiedItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID int64
		}
		// GetClassifiedItems holds details about calls to the GetClassifiedItems method.
		GetClassifiedItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MinScore is the minScore argument value.
			MinScore float64
			// Topic is the topic argument value.
			Topic string
			// Limit is the limit argument value.
			Limit int
		}
		// GetClassifiedItemsCount holds details about calls to the GetClassifiedItemsCount method.
		GetClassifiedItemsCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req domain.ArticlesRequest
		}
		// GetClassifiedItemsWithFilters holds details about calls to the GetClassifiedItemsWithFilters method.
		GetClassifiedItemsWithFilters []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req domain.ArticlesRequest
		}
		// GetFeedByName holds details about calls to the GetFeedByName method.
		GetFeedByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetFeeds holds details about calls to the GetFeeds method.
		GetFeeds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetGrouping holds details about calls to the GetGrouping method.
		GetGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetGroupingBySlug holds details about calls to the GetGroupingBySlug method.
		GetGroupingBySlug []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slug is the slug argument value.
			Slug string
		}
		// GetItems holds details about calls to the GetItems method.
		GetItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetSearchItemsCount holds details about calls to the GetSearchItemsCount method.
		GetSearchItemsCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SearchQuery is the searchQuery argument value.
			SearchQuery string
			// Req is the req argument value.
			Req domain.ArticlesRequest
		}
		// GetSetting holds details about calls to the GetSetting method.
		GetSetting []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetTopTopicsByScore holds details about calls to the GetTopTopicsByScore method.
		GetTopTopicsByScore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MinScore is the minScore argument value.
			MinScore float64
			// Limit is the limit argument value.
			Limit int
		}
		// GetTopics holds details about calls to the GetTopics method.
		GetTopics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetTopicsFiltered holds details about calls to the GetTopicsFiltered method.
		GetTopicsFiltered []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MinScore is the minScore argument value.
			MinScore float64
		}
		// GroupingCounts holds details about calls to the GroupingCounts method.
		GroupingCounts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListBeats holds details about calls to the ListBeats method.
		ListBeats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts repository.ListBeatsOptions
		}
		// ListGroupings holds details about calls to the ListGroupings method.
		ListGroupings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListTitleRevisions holds details about calls to the ListTitleRevisions method.
		ListTitleRevisions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
		// MarkViewed holds details about calls to the MarkViewed method.
		MarkViewed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
		}
		// ReorderGroupings holds details about calls to the ReorderGroupings method.
		ReorderGroupings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdsInOrder is the idsInOrder argument value.
			IdsInOrder []int64
		}
		// SearchBeatsWithMembers holds details about calls to the SearchBeatsWithMembers method.
		SearchBeatsWithMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
		// SearchItems holds details about calls to the SearchItems method.
		SearchItems []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SearchQuery is the searchQuery argument value.
			SearchQuery string
			// Req is the req argument value.
			Req domain.ArticlesRequest
		}
		// SetFeedback holds details about calls to the SetFeedback method.
		SetFeedback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeatID is the beatID argument value.
			BeatID int64
			// Feedback is the feedback argument value.
			Feedback string
		}
		// SetSetting holds details about calls to the SetSetting method.
		SetSetting []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
		// SuggestTags holds details about calls to the SuggestTags method.
		SuggestTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Prefix is the prefix argument value.
			Prefix string
			// Limit is the limit argument value.
			Limit int
		}
		// UpdateFeed holds details about calls to the UpdateFeed method.
		UpdateFeed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FeedID is the feedID argument value.
			FeedID int64
			// Title is the title argument value.
			Title string
			// FeedURL is the feedURL argument value.
			FeedURL string
			// IconURL is the iconURL argument value.
			IconURL string
			// FetchInterval is the fetchInterval argument value.
			FetchInterval time.Duration
		}
		// UpdateFeedStatus holds details about calls to the UpdateFeedStatus method.
		UpdateFeedStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FeedID is the feedID argument value.
			FeedID int64
			// Enabled is the enabled argument value.
			Enabled bool
		}
		// UpdateGrouping holds details about calls to the UpdateGrouping method.
		UpdateGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// G is the g argument value.
			G domain.Grouping
		}
		// UpdateItemFeedback holds details about calls to the UpdateItemFeedback method.
		UpdateItemFeedback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ItemID is the itemID argument value.
			ItemID int64
			// Feedback is the feedback argument value.
			Feedback string
		}
	}
	lockCreateFeed                    sync.RWMutex
	lockCreateGrouping                sync.RWMutex
	lockDeleteFeed                    sync.RWMutex
	lockDeleteGrouping                sync.RWMutex
	lockGetActiveFeedNames            sync.RWMutex
	lockGetAllFeeds                   sync.RWMutex
	lockGetBeat                       sync.RWMutex
	lockGetBigTags                    sync.RWMutex
	lockGetClassifiedItem             sync.RWMutex
	lockGetClassifiedItems            sync.RWMutex
	lockGetClassifiedItemsCount       sync.RWMutex
	lockGetClassifiedItemsWithFilters sync.RWMutex
	lockGetFeedByName                 sync.RWMutex
	lockGetFeeds                      sync.RWMutex
	lockGetGrouping                   sync.RWMutex
	lockGetGroupingBySlug             sync.RWMutex
	lockGetItems                      sync.RWMutex
	lockGetSearchItemsCount           sync.RWMutex
	lockGetSetting                    sync.RWMutex
	lockGetTopTopicsByScore           sync.RWMutex
	lockGetTopics                     sync.RWMutex
	lockGetTopicsFiltered             sync.RWMutex
	lockGroupingCounts                sync.RWMutex
	lockListBeats                     sync.RWMutex
	lockListGroupings                 sync.RWMutex
	lockListTitleRevisions            sync.RWMutex
	lockMarkViewed                    sync.RWMutex
	lockReorderGroupings              sync.RWMutex
	lockSearchBeatsWithMembers        sync.RWMutex
	lockSearchItems                   sync.RWMutex
	lockSetFeedback                   sync.RWMutex
	lockSetSetting                    sync.RWMutex
	lockSuggestTags                   sync.RWMutex
	lockUpdateFeed                    sync.RWMutex
	lockUpdateFeedStatus              sync.RWMutex
	lockUpdateGrouping                sync.RWMutex
	lockUpdateItemFeedback            sync.RWMutex
}

// CreateFeed calls CreateFeedFunc.
func (mock *DatabaseMock) CreateFeed(ctx context.Context, feed *domain.Feed) error {
	if mock.CreateFeedFunc == nil {
		panic("DatabaseMock.CreateFeedFunc: method is nil but Database.CreateFeed was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Feed *domain.Feed
	}{
		Ctx:  ctx,
		Feed: feed,
	}
	mock.lockCreateFeed.Lock()
	mock.calls.CreateFeed = append(mock.calls.CreateFeed, callInfo)
	mock.lockCreateFeed.Unlock()
	return mock.CreateFeedFunc(ctx, feed)
}

// CreateFeedCalls gets all the calls that were made to CreateFeed.
// Check the length with:
//
//	len(mockedDatabase.CreateFeedCalls())
func (mock *DatabaseMock) CreateFeedCalls() []struct {
	Ctx  context.Context
	Feed *domain.Feed
} {
	var calls []struct {
		Ctx  context.Context
		Feed *domain.Feed
	}
	mock.lockCreateFeed.RLock()
	calls = mock.calls.CreateFeed
	mock.lockCreateFeed.RUnlock()
	return calls
}

// CreateGrouping calls CreateGroupingFunc.
func (mock *DatabaseMock) CreateGrouping(ctx context.Context, g domain.Grouping) (int64, error) {
	if mock.CreateGroupingFunc == nil {
		panic("DatabaseMock.CreateGroupingFunc: method is nil but Database.CreateGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		G   domain.Grouping
	}{
		Ctx: ctx,
		G:   g,
	}
	mock.lockCreateGrouping.Lock()
	mock.calls.CreateGrouping = append(mock.calls.CreateGrouping, callInfo)
	mock.lockCreateGrouping.Unlock()
	return mock.CreateGroupingFunc(ctx, g)
}

// CreateGroupingCalls gets all the calls that were made to CreateGrouping.
// Check the length with:
//
//	len(mockedDatabase.CreateGroupingCalls())
func (mock *DatabaseMock) CreateGroupingCalls() []struct {
	Ctx context.Context
	G   domain.Grouping
} {
	var calls []struct {
		Ctx context.Context
		G   domain.Grouping
	}
	mock.lockCreateGrouping.RLock()
	calls = mock.calls.CreateGrouping
	mock.lockCreateGrouping.RUnlock()
	return calls
}

// DeleteFeed calls DeleteFeedFunc.
func (mock *DatabaseMock) DeleteFeed(ctx context.Context, feedID int64) error {
	if mock.DeleteFeedFunc == nil {
		panic("DatabaseMock.DeleteFeedFunc: method is nil but Database.DeleteFeed was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		FeedID int64
	}{
		Ctx:    ctx,
		FeedID: feedID,
	}
	mock.lockDeleteFeed.Lock()
	mock.calls.DeleteFeed = append(mock.calls.DeleteFeed, callInfo)
	mock.lockDeleteFeed.Unlock()
	return mock.DeleteFeedFunc(ctx, feedID)
}

// DeleteFeedCalls gets all the calls that were made to DeleteFeed.
// Check the length with:
//
//	len(mockedDatabase.DeleteFeedCalls())
func (mock *DatabaseMock) DeleteFeedCalls() []struct {
	Ctx    context.Context
	FeedID int64
} {
	var calls []struct {
		Ctx    context.Context
		FeedID int64
	}
	mock.lockDeleteFeed.RLock()
	calls = mock.calls.DeleteFeed
	mock.lockDeleteFeed.RUnlock()
	return calls
}

// DeleteGrouping calls DeleteGroupingFunc.
func (mock *DatabaseMock) DeleteGrouping(ctx context.Context, id int64) error {
	if mock.DeleteGroupingFunc == nil {
		panic("DatabaseMock.DeleteGroupingFunc: method is nil but Database.DeleteGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteGrouping.Lock()
	mock.calls.DeleteGrouping = append(mock.calls.DeleteGrouping, callInfo)
	mock.lockDeleteGrouping.Unlock()
	return mock.DeleteGroupingFunc(ctx, id)
}

// DeleteGroupingCalls gets all the calls that were made to DeleteGrouping.
// Check the length with:
//
//	len(mockedDatabase.DeleteGroupingCalls())
func (mock *DatabaseMock) DeleteGroupingCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteGrouping.RLock()
	calls = mock.calls.DeleteGrouping
	mock.lockDeleteGrouping.RUnlock()
	return calls
}

// GetActiveFeedNames calls GetActiveFeedNamesFunc.
func (mock *DatabaseMock) GetActiveFeedNames(ctx context.Context, minScore float64) ([]string, error) {
	if mock.GetActiveFeedNamesFunc == nil {
		panic("DatabaseMock.GetActiveFeedNamesFunc: method is nil but Database.GetActiveFeedNames was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MinScore float64
	}{
		Ctx:      ctx,
		MinScore: minScore,
	}
	mock.lockGetActiveFeedNames.Lock()
	mock.calls.GetActiveFeedNames = append(mock.calls.GetActiveFeedNames, callInfo)
	mock.lockGetActiveFeedNames.Unlock()
	return mock.GetActiveFeedNamesFunc(ctx, minScore)
}

// GetActiveFeedNamesCalls gets all the calls that were made to GetActiveFeedNames.
// Check the length with:
//
//	len(mockedDatabase.GetActiveFeedNamesCalls())
func (mock *DatabaseMock) GetActiveFeedNamesCalls() []struct {
	Ctx      context.Context
	MinScore float64
} {
	var calls []struct {
		Ctx      context.Context
		MinScore float64
	}
	mock.lockGetActiveFeedNames.RLock()
	calls = mock.calls.GetActiveFeedNames
	mock.lockGetActiveFeedNames.RUnlock()
	return calls
}

// GetAllFeeds calls GetAllFeedsFunc.
func (mock *DatabaseMock) GetAllFeeds(ctx context.Context) ([]domain.Feed, error) {
	if mock.GetAllFeedsFunc == nil {
		panic("DatabaseMock.GetAllFeedsFunc: method is nil but Database.GetAllFeeds was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllFeeds.Lock()
	mock.calls.GetAllFeeds = append(mock.calls.GetAllFeeds, callInfo)
	mock.lockGetAllFeeds.Unlock()
	return mock.GetAllFeedsFunc(ctx)
}

// GetAllFeedsCalls gets all the calls that were made to GetAllFeeds.
// Check the length with:
//
//	len(mockedDatabase.GetAllFeedsCalls())
func (mock *DatabaseMock) GetAllFeedsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllFeeds.RLock()
	calls = mock.calls.GetAllFeeds
	mock.lockGetAllFeeds.RUnlock()
	return calls
}

// GetBeat calls GetBeatFunc.
func (mock *DatabaseMock) GetBeat(ctx context.Context, beatID int64) (domain.BeatWithMembers, error) {
	if mock.GetBeatFunc == nil {
		panic("DatabaseMock.GetBeatFunc: method is nil but Database.GetBeat was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockGetBeat.Lock()
	mock.calls.GetBeat = append(mock.calls.GetBeat, callInfo)
	mock.lockGetBeat.Unlock()
	return mock.GetBeatFunc(ctx, beatID)
}

// GetBeatCalls gets all the calls that were made to GetBeat.
// Check the length with:
//
//	len(mockedDatabase.GetBeatCalls())
func (mock *DatabaseMock) GetBeatCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockGetBeat.RLock()
	calls = mock.calls.GetBeat
	mock.lockGetBeat.RUnlock()
	return calls
}

// GetBigTags calls GetBigTagsFunc.
func (mock *DatabaseMock) GetBigTags(ctx context.Context, threshold int) (map[string]int, error) {
	if mock.GetBigTagsFunc == nil {
		panic("DatabaseMock.GetBigTagsFunc: method is nil but Database.GetBigTags was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Threshold int
	}{
		Ctx:       ctx,
		Threshold: threshold,
	}
	mock.lockGetBigTags.Lock()
	mock.calls.GetBigTags = append(mock.calls.GetBigTags, callInfo)
	mock.lockGetBigTags.Unlock()
	return mock.GetBigTagsFunc(ctx, threshold)
}

// GetBigTagsCalls gets all the calls that were made to GetBigTags.
// Check the length with:
//
//	len(mockedDatabase.GetBigTagsCalls())
func (mock *DatabaseMock) GetBigTagsCalls() []struct {
	Ctx       context.Context
	Threshold int
} {
	var calls []struct {
		Ctx       context.Context
		Threshold int
	}
	mock.lockGetBigTags.RLock()
	calls = mock.calls.GetBigTags
	mock.lockGetBigTags.RUnlock()
	return calls
}

// GetClassifiedItem calls GetClassifiedItemFunc.
func (mock *DatabaseMock) GetClassifiedItem(ctx context.Context, itemID int64) (*domain.ClassifiedItem, error) {
	if mock.GetClassifiedItemFunc == nil {
		panic("DatabaseMock.GetClassifiedItemFunc: method is nil but Database.GetClassifiedItem was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ItemID int64
	}{
		Ctx:    ctx,
		ItemID: itemID,
	}
	mock.lockGetClassifiedItem.Lock()
	mock.calls.GetClassifiedItem = append(mock.calls.GetClassifiedItem, callInfo)
	mock.lockGetClassifiedItem.Unlock()
	return mock.GetClassifiedItemFunc(ctx, itemID)
}

// GetClassifiedItemCalls gets all the calls that were made to GetClassifiedItem.
// Check the length with:
//
//	len(mockedDatabase.GetClassifiedItemCalls())
func (mock *DatabaseMock) GetClassifiedItemCalls() []struct {
	Ctx    context.Context
	ItemID int64
} {
	var calls []struct {
		Ctx    context.Context
		ItemID int64
	}
	mock.lockGetClassifiedItem.RLock()
	calls = mock.calls.GetClassifiedItem
	mock.lockGetClassifiedItem.RUnlock()
	return calls
}

// GetClassifiedItems calls GetClassifiedItemsFunc.
func (mock *DatabaseMock) GetClassifiedItems(ctx context.Context, minScore float64, topic string, limit int) ([]domain.ClassifiedItem, error) {
	if mock.GetClassifiedItemsFunc == nil {
		panic("DatabaseMock.GetClassifiedItemsFunc: method is nil but Database.GetClassifiedItems was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MinScore float64
		Topic    string
		Limit    int
	}{
		Ctx:      ctx,
		MinScore: minScore,
		Topic:    topic,
		Limit:    limit,
	}
	mock.lockGetClassifiedItems.Lock()
	mock.calls.GetClassifiedItems = append(mock.calls.GetClassifiedItems, callInfo)
	mock.lockGetClassifiedItems.Unlock()
	return mock.GetClassifiedItemsFunc(ctx, minScore, topic, limit)
}

// GetClassifiedItemsCalls gets all the calls that were made to GetClassifiedItems.
// Check the length with:
//
//	len(mockedDatabase.GetClassifiedItemsCalls())
func (mock *DatabaseMock) GetClassifiedItemsCalls() []struct {
	Ctx      context.Context
	MinScore float64
	Topic    string
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		MinScore float64
		Topic    string
		Limit    int
	}
	mock.lockGetClassifiedItems.RLock()
	calls = mock.calls.GetClassifiedItems
	mock.lockGetClassifiedItems.RUnlock()
	return calls
}

// GetClassifiedItemsCount calls GetClassifiedItemsCountFunc.
func (mock *DatabaseMock) GetClassifiedItemsCount(ctx context.Context, req domain.ArticlesRequest) (int, error) {
	if mock.GetClassifiedItemsCountFunc == nil {
		panic("DatabaseMock.GetClassifiedItemsCountFunc: method is nil but Database.GetClassifiedItemsCount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req domain.ArticlesRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetClassifiedItemsCount.Lock()
	mock.calls.GetClassifiedItemsCount = append(mock.calls.GetClassifiedItemsCount, callInfo)
	mock.lockGetClassifiedItemsCount.Unlock()
	return mock.GetClassifiedItemsCountFunc(ctx, req)
}

// GetClassifiedItemsCountCalls gets all the calls that were made to GetClassifiedItemsCount.
// Check the length with:
//
//	len(mockedDatabase.GetClassifiedItemsCountCalls())
func (mock *DatabaseMock) GetClassifiedItemsCountCalls() []struct {
	Ctx context.Context
	Req domain.ArticlesRequest
} {
	var calls []struct {
		Ctx context.Context
		Req domain.ArticlesRequest
	}
	mock.lockGetClassifiedItemsCount.RLock()
	calls = mock.calls.GetClassifiedItemsCount
	mock.lockGetClassifiedItemsCount.RUnlock()
	return calls
}

// GetClassifiedItemsWithFilters calls GetClassifiedItemsWithFiltersFunc.
func (mock *DatabaseMock) GetClassifiedItemsWithFilters(ctx context.Context, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error) {
	if mock.GetClassifiedItemsWithFiltersFunc == nil {
		panic("DatabaseMock.GetClassifiedItemsWithFiltersFunc: method is nil but Database.GetClassifiedItemsWithFilters was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req domain.ArticlesRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetClassifiedItemsWithFilters.Lock()
	mock.calls.GetClassifiedItemsWithFilters = append(mock.calls.GetClassifiedItemsWithFilters, callInfo)
	mock.lockGetClassifiedItemsWithFilters.Unlock()
	return mock.GetClassifiedItemsWithFiltersFunc(ctx, req)
}

// GetClassifiedItemsWithFiltersCalls gets all the calls that were made to GetClassifiedItemsWithFilters.
// Check the length with:
//
//	len(mockedDatabase.GetClassifiedItemsWithFiltersCalls())
func (mock *DatabaseMock) GetClassifiedItemsWithFiltersCalls() []struct {
	Ctx context.Context
	Req domain.ArticlesRequest
} {
	var calls []struct {
		Ctx context.Context
		Req domain.ArticlesRequest
	}
	mock.lockGetClassifiedItemsWithFilters.RLock()
	calls = mock.calls.GetClassifiedItemsWithFilters
	mock.lockGetClassifiedItemsWithFilters.RUnlock()
	return calls
}

// GetFeedByName calls GetFeedByNameFunc.
func (mock *DatabaseMock) GetFeedByName(ctx context.Context, name string) (*domain.Feed, error) {
	if mock.GetFeedByNameFunc == nil {
		panic("DatabaseMock.GetFeedByNameFunc: method is nil but Database.GetFeedByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetFeedByName.Lock()
	mock.calls.GetFeedByName = append(mock.calls.GetFeedByName, callInfo)
	mock.lockGetFeedByName.Unlock()
	return mock.GetFeedByNameFunc(ctx, name)
}

// GetFeedByNameCalls gets all the calls that were made to GetFeedByName.
// Check the length with:
//
//	len(mockedDatabase.GetFeedByNameCalls())
func (mock *DatabaseMock) GetFeedByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetFeedByName.RLock()
	calls = mock.calls.GetFeedByName
	mock.lockGetFeedByName.RUnlock()
	return calls
}

// GetFeeds calls GetFeedsFunc.
func (mock *DatabaseMock) GetFeeds(ctx context.Context) ([]domain.Feed, error) {
	if mock.GetFeedsFunc == nil {
		panic("DatabaseMock.GetFeedsFunc: method is nil but Database.GetFeeds was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetFeeds.Lock()
	mock.calls.GetFeeds = append(mock.calls.GetFeeds, callInfo)
	mock.lockGetFeeds.Unlock()
	return mock.GetFeedsFunc(ctx)
}

// GetFeedsCalls gets all the calls that were made to GetFeeds.
// Check the length with:
//
//	len(mockedDatabase.GetFeedsCalls())
func (mock *DatabaseMock) GetFeedsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetFeeds.RLock()
	calls = mock.calls.GetFeeds
	mock.lockGetFeeds.RUnlock()
	return calls
}

// GetGrouping calls GetGroupingFunc.
func (mock *DatabaseMock) GetGrouping(ctx context.Context, id int64) (domain.Grouping, error) {
	if mock.GetGroupingFunc == nil {
		panic("DatabaseMock.GetGroupingFunc: method is nil but Database.GetGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetGrouping.Lock()
	mock.calls.GetGrouping = append(mock.calls.GetGrouping, callInfo)
	mock.lockGetGrouping.Unlock()
	return mock.GetGroupingFunc(ctx, id)
}

// GetGroupingCalls gets all the calls that were made to GetGrouping.
// Check the length with:
//
//	len(mockedDatabase.GetGroupingCalls())
func (mock *DatabaseMock) GetGroupingCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetGrouping.RLock()
	calls = mock.calls.GetGrouping
	mock.lockGetGrouping.RUnlock()
	return calls
}

// GetGroupingBySlug calls GetGroupingBySlugFunc.
func (mock *DatabaseMock) GetGroupingBySlug(ctx context.Context, slug string) (domain.Grouping, error) {
	if mock.GetGroupingBySlugFunc == nil {
		panic("DatabaseMock.GetGroupingBySlugFunc: method is nil but Database.GetGroupingBySlug was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Slug string
	}{
		Ctx:  ctx,
		Slug: slug,
	}
	mock.lockGetGroupingBySlug.Lock()
	mock.calls.GetGroupingBySlug = append(mock.calls.GetGroupingBySlug, callInfo)
	mock.lockGetGroupingBySlug.Unlock()
	return mock.GetGroupingBySlugFunc(ctx, slug)
}

// GetGroupingBySlugCalls gets all the calls that were made to GetGroupingBySlug.
// Check the length with:
//
//	len(mockedDatabase.GetGroupingBySlugCalls())
func (mock *DatabaseMock) GetGroupingBySlugCalls() []struct {
	Ctx  context.Context
	Slug string
} {
	var calls []struct {
		Ctx  context.Context
		Slug string
	}
	mock.lockGetGroupingBySlug.RLock()
	calls = mock.calls.GetGroupingBySlug
	mock.lockGetGroupingBySlug.RUnlock()
	return calls
}

// GetItems calls GetItemsFunc.
func (mock *DatabaseMock) GetItems(ctx context.Context, limit int, offset int) ([]domain.Item, error) {
	if mock.GetItemsFunc == nil {
		panic("DatabaseMock.GetItemsFunc: method is nil but Database.GetItems was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetItems.Lock()
	mock.calls.GetItems = append(mock.calls.GetItems, callInfo)
	mock.lockGetItems.Unlock()
	return mock.GetItemsFunc(ctx, limit, offset)
}

// GetItemsCalls gets all the calls that were made to GetItems.
// Check the length with:
//
//	len(mockedDatabase.GetItemsCalls())
func (mock *DatabaseMock) GetItemsCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockGetItems.RLock()
	calls = mock.calls.GetItems
	mock.lockGetItems.RUnlock()
	return calls
}

// GetSearchItemsCount calls GetSearchItemsCountFunc.
func (mock *DatabaseMock) GetSearchItemsCount(ctx context.Context, searchQuery string, req domain.ArticlesRequest) (int, error) {
	if mock.GetSearchItemsCountFunc == nil {
		panic("DatabaseMock.GetSearchItemsCountFunc: method is nil but Database.GetSearchItemsCount was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		SearchQuery string
		Req         domain.ArticlesRequest
	}{
		Ctx:         ctx,
		SearchQuery: searchQuery,
		Req:         req,
	}
	mock.lockGetSearchItemsCount.Lock()
	mock.calls.GetSearchItemsCount = append(mock.calls.GetSearchItemsCount, callInfo)
	mock.lockGetSearchItemsCount.Unlock()
	return mock.GetSearchItemsCountFunc(ctx, searchQuery, req)
}

// GetSearchItemsCountCalls gets all the calls that were made to GetSearchItemsCount.
// Check the length with:
//
//	len(mockedDatabase.GetSearchItemsCountCalls())
func (mock *DatabaseMock) GetSearchItemsCountCalls() []struct {
	Ctx         context.Context
	SearchQuery string
	Req         domain.ArticlesRequest
} {
	var calls []struct {
		Ctx         context.Context
		SearchQuery string
		Req         domain.ArticlesRequest
	}
	mock.lockGetSearchItemsCount.RLock()
	calls = mock.calls.GetSearchItemsCount
	mock.lockGetSearchItemsCount.RUnlock()
	return calls
}

// GetSetting calls GetSettingFunc.
func (mock *DatabaseMock) GetSetting(ctx context.Context, key string) (string, error) {
	if mock.GetSettingFunc == nil {
		panic("DatabaseMock.GetSettingFunc: method is nil but Database.GetSetting was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetSetting.Lock()
	mock.calls.GetSetting = append(mock.calls.GetSetting, callInfo)
	mock.lockGetSetting.Unlock()
	return mock.GetSettingFunc(ctx, key)
}

// GetSettingCalls gets all the calls that were made to GetSetting.
// Check the length with:
//
//	len(mockedDatabase.GetSettingCalls())
func (mock *DatabaseMock) GetSettingCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetSetting.RLock()
	calls = mock.calls.GetSetting
	mock.lockGetSetting.RUnlock()
	return calls
}

// GetTopTopicsByScore calls GetTopTopicsByScoreFunc.
func (mock *DatabaseMock) GetTopTopicsByScore(ctx context.Context, minScore float64, limit int) ([]domain.TopicWithScore, error) {
	if mock.GetTopTopicsByScoreFunc == nil {
		panic("DatabaseMock.GetTopTopicsByScoreFunc: method is nil but Database.GetTopTopicsByScore was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MinScore float64
		Limit    int
	}{
		Ctx:      ctx,
		MinScore: minScore,
		Limit:    limit,
	}
	mock.lockGetTopTopicsByScore.Lock()
	mock.calls.GetTopTopicsByScore = append(mock.calls.GetTopTopicsByScore, callInfo)
	mock.lockGetTopTopicsByScore.Unlock()
	return mock.GetTopTopicsByScoreFunc(ctx, minScore, limit)
}

// GetTopTopicsByScoreCalls gets all the calls that were made to GetTopTopicsByScore.
// Check the length with:
//
//	len(mockedDatabase.GetTopTopicsByScoreCalls())
func (mock *DatabaseMock) GetTopTopicsByScoreCalls() []struct {
	Ctx      context.Context
	MinScore float64
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		MinScore float64
		Limit    int
	}
	mock.lockGetTopTopicsByScore.RLock()
	calls = mock.calls.GetTopTopicsByScore
	mock.lockGetTopTopicsByScore.RUnlock()
	return calls
}

// GetTopics calls GetTopicsFunc.
func (mock *DatabaseMock) GetTopics(ctx context.Context) ([]string, error) {
	if mock.GetTopicsFunc == nil {
		panic("DatabaseMock.GetTopicsFunc: method is nil but Database.GetTopics was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTopics.Lock()
	mock.calls.GetTopics = append(mock.calls.GetTopics, callInfo)
	mock.lockGetTopics.Unlock()
	return mock.GetTopicsFunc(ctx)
}

// GetTopicsCalls gets all the calls that were made to GetTopics.
// Check the length with:
//
//	len(mockedDatabase.GetTopicsCalls())
func (mock *DatabaseMock) GetTopicsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTopics.RLock()
	calls = mock.calls.GetTopics
	mock.lockGetTopics.RUnlock()
	return calls
}

// GetTopicsFiltered calls GetTopicsFilteredFunc.
func (mock *DatabaseMock) GetTopicsFiltered(ctx context.Context, minScore float64) ([]string, error) {
	if mock.GetTopicsFilteredFunc == nil {
		panic("DatabaseMock.GetTopicsFilteredFunc: method is nil but Database.GetTopicsFiltered was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MinScore float64
	}{
		Ctx:      ctx,
		MinScore: minScore,
	}
	mock.lockGetTopicsFiltered.Lock()
	mock.calls.GetTopicsFiltered = append(mock.calls.GetTopicsFiltered, callInfo)
	mock.lockGetTopicsFiltered.Unlock()
	return mock.GetTopicsFilteredFunc(ctx, minScore)
}

// GetTopicsFilteredCalls gets all the calls that were made to GetTopicsFiltered.
// Check the length with:
//
//	len(mockedDatabase.GetTopicsFilteredCalls())
func (mock *DatabaseMock) GetTopicsFilteredCalls() []struct {
	Ctx      context.Context
	MinScore float64
} {
	var calls []struct {
		Ctx      context.Context
		MinScore float64
	}
	mock.lockGetTopicsFiltered.RLock()
	calls = mock.calls.GetTopicsFiltered
	mock.lockGetTopicsFiltered.RUnlock()
	return calls
}

// GroupingCounts calls GroupingCountsFunc.
func (mock *DatabaseMock) GroupingCounts(ctx context.Context) (map[int64]int, error) {
	if mock.GroupingCountsFunc == nil {
		panic("DatabaseMock.GroupingCountsFunc: method is nil but Database.GroupingCounts was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGroupingCounts.Lock()
	mock.calls.GroupingCounts = append(mock.calls.GroupingCounts, callInfo)
	mock.lockGroupingCounts.Unlock()
	return mock.GroupingCountsFunc(ctx)
}

// GroupingCountsCalls gets all the calls that were made to GroupingCounts.
// Check the length with:
//
//	len(mockedDatabase.GroupingCountsCalls())
func (mock *DatabaseMock) GroupingCountsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGroupingCounts.RLock()
	calls = mock.calls.GroupingCounts
	mock.lockGroupingCounts.RUnlock()
	return calls
}

// ListBeats calls ListBeatsFunc.
func (mock *DatabaseMock) ListBeats(ctx context.Context, opts repository.ListBeatsOptions) ([]domain.BeatWithMembers, error) {
	if mock.ListBeatsFunc == nil {
		panic("DatabaseMock.ListBeatsFunc: method is nil but Database.ListBeats was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts repository.ListBeatsOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockListBeats.Lock()
	mock.calls.ListBeats = append(mock.calls.ListBeats, callInfo)
	mock.lockListBeats.Unlock()
	return mock.ListBeatsFunc(ctx, opts)
}

// ListBeatsCalls gets all the calls that were made to ListBeats.
// Check the length with:
//
//	len(mockedDatabase.ListBeatsCalls())
func (mock *DatabaseMock) ListBeatsCalls() []struct {
	Ctx  context.Context
	Opts repository.ListBeatsOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts repository.ListBeatsOptions
	}
	mock.lockListBeats.RLock()
	calls = mock.calls.ListBeats
	mock.lockListBeats.RUnlock()
	return calls
}

// ListGroupings calls ListGroupingsFunc.
func (mock *DatabaseMock) ListGroupings(ctx context.Context) ([]domain.Grouping, error) {
	if mock.ListGroupingsFunc == nil {
		panic("DatabaseMock.ListGroupingsFunc: method is nil but Database.ListGroupings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListGroupings.Lock()
	mock.calls.ListGroupings = append(mock.calls.ListGroupings, callInfo)
	mock.lockListGroupings.Unlock()
	return mock.ListGroupingsFunc(ctx)
}

// ListGroupingsCalls gets all the calls that were made to ListGroupings.
// Check the length with:
//
//	len(mockedDatabase.ListGroupingsCalls())
func (mock *DatabaseMock) ListGroupingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListGroupings.RLock()
	calls = mock.calls.ListGroupings
	mock.lockListGroupings.RUnlock()
	return calls
}

// ListTitleRevisions calls ListTitleRevisionsFunc.
func (mock *DatabaseMock) ListTitleRevisions(ctx context.Context, beatID int64) ([]domain.TitleRevision, error) {
	if mock.ListTitleRevisionsFunc == nil {
		panic("DatabaseMock.ListTitleRevisionsFunc: method is nil but Database.ListTitleRevisions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockListTitleRevisions.Lock()
	mock.calls.ListTitleRevisions = append(mock.calls.ListTitleRevisions, callInfo)
	mock.lockListTitleRevisions.Unlock()
	return mock.ListTitleRevisionsFunc(ctx, beatID)
}

// ListTitleRevisionsCalls gets all the calls that were made to ListTitleRevisions.
// Check the length with:
//
//	len(mockedDatabase.ListTitleRevisionsCalls())
func (mock *DatabaseMock) ListTitleRevisionsCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockListTitleRevisions.RLock()
	calls = mock.calls.ListTitleRevisions
	mock.lockListTitleRevisions.RUnlock()
	return calls
}

// MarkViewed calls MarkViewedFunc.
func (mock *DatabaseMock) MarkViewed(ctx context.Context, beatID int64) error {
	if mock.MarkViewedFunc == nil {
		panic("DatabaseMock.MarkViewedFunc: method is nil but Database.MarkViewed was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		BeatID int64
	}{
		Ctx:    ctx,
		BeatID: beatID,
	}
	mock.lockMarkViewed.Lock()
	mock.calls.MarkViewed = append(mock.calls.MarkViewed, callInfo)
	mock.lockMarkViewed.Unlock()
	return mock.MarkViewedFunc(ctx, beatID)
}

// MarkViewedCalls gets all the calls that were made to MarkViewed.
// Check the length with:
//
//	len(mockedDatabase.MarkViewedCalls())
func (mock *DatabaseMock) MarkViewedCalls() []struct {
	Ctx    context.Context
	BeatID int64
} {
	var calls []struct {
		Ctx    context.Context
		BeatID int64
	}
	mock.lockMarkViewed.RLock()
	calls = mock.calls.MarkViewed
	mock.lockMarkViewed.RUnlock()
	return calls
}

// ReorderGroupings calls ReorderGroupingsFunc.
func (mock *DatabaseMock) ReorderGroupings(ctx context.Context, idsInOrder []int64) error {
	if mock.ReorderGroupingsFunc == nil {
		panic("DatabaseMock.ReorderGroupingsFunc: method is nil but Database.ReorderGroupings was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		IdsInOrder []int64
	}{
		Ctx:        ctx,
		IdsInOrder: idsInOrder,
	}
	mock.lockReorderGroupings.Lock()
	mock.calls.ReorderGroupings = append(mock.calls.ReorderGroupings, callInfo)
	mock.lockReorderGroupings.Unlock()
	return mock.ReorderGroupingsFunc(ctx, idsInOrder)
}

// ReorderGroupingsCalls gets all the calls that were made to ReorderGroupings.
// Check the length with:
//
//	len(mockedDatabase.ReorderGroupingsCalls())
func (mock *DatabaseMock) ReorderGroupingsCalls() []struct {
	Ctx        context.Context
	IdsInOrder []int64
} {
	var calls []struct {
		Ctx        context.Context
		IdsInOrder []int64
	}
	mock.lockReorderGroupings.RLock()
	calls = mock.calls.ReorderGroupings
	mock.lockReorderGroupings.RUnlock()
	return calls
}

// SearchBeatsWithMembers calls SearchBeatsWithMembersFunc.
func (mock *DatabaseMock) SearchBeatsWithMembers(ctx context.Context, query string, limit int) ([]domain.BeatWithMembers, error) {
	if mock.SearchBeatsWithMembersFunc == nil {
		panic("DatabaseMock.SearchBeatsWithMembersFunc: method is nil but Database.SearchBeatsWithMembers was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Limit int
	}{
		Ctx:   ctx,
		Query: query,
		Limit: limit,
	}
	mock.lockSearchBeatsWithMembers.Lock()
	mock.calls.SearchBeatsWithMembers = append(mock.calls.SearchBeatsWithMembers, callInfo)
	mock.lockSearchBeatsWithMembers.Unlock()
	return mock.SearchBeatsWithMembersFunc(ctx, query, limit)
}

// SearchBeatsWithMembersCalls gets all the calls that were made to SearchBeatsWithMembers.
// Check the length with:
//
//	len(mockedDatabase.SearchBeatsWithMembersCalls())
func (mock *DatabaseMock) SearchBeatsWithMembersCalls() []struct {
	Ctx   context.Context
	Query string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Limit int
	}
	mock.lockSearchBeatsWithMembers.RLock()
	calls = mock.calls.SearchBeatsWithMembers
	mock.lockSearchBeatsWithMembers.RUnlock()
	return calls
}

// SearchItems calls SearchItemsFunc.
func (mock *DatabaseMock) SearchItems(ctx context.Context, searchQuery string, req domain.ArticlesRequest) ([]domain.ClassifiedItem, error) {
	if mock.SearchItemsFunc == nil {
		panic("DatabaseMock.SearchItemsFunc: method is nil but Database.SearchItems was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		SearchQuery string
		Req         domain.ArticlesRequest
	}{
		Ctx:         ctx,
		SearchQuery: searchQuery,
		Req:         req,
	}
	mock.lockSearchItems.Lock()
	mock.calls.SearchItems = append(mock.calls.SearchItems, callInfo)
	mock.lockSearchItems.Unlock()
	return mock.SearchItemsFunc(ctx, searchQuery, req)
}

// SearchItemsCalls gets all the calls that were made to SearchItems.
// Check the length with:
//
//	len(mockedDatabase.SearchItemsCalls())
func (mock *DatabaseMock) SearchItemsCalls() []struct {
	Ctx         context.Context
	SearchQuery string
	Req         domain.ArticlesRequest
} {
	var calls []struct {
		Ctx         context.Context
		SearchQuery string
		Req         domain.ArticlesRequest
	}
	mock.lockSearchItems.RLock()
	calls = mock.calls.SearchItems
	mock.lockSearchItems.RUnlock()
	return calls
}

// SetFeedback calls SetFeedbackFunc.
func (mock *DatabaseMock) SetFeedback(ctx context.Context, beatID int64, feedback string) error {
	if mock.SetFeedbackFunc == nil {
		panic("DatabaseMock.SetFeedbackFunc: method is nil but Database.SetFeedback was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BeatID   int64
		Feedback string
	}{
		Ctx:      ctx,
		BeatID:   beatID,
		Feedback: feedback,
	}
	mock.lockSetFeedback.Lock()
	mock.calls.SetFeedback = append(mock.calls.SetFeedback, callInfo)
	mock.lockSetFeedback.Unlock()
	return mock.SetFeedbackFunc(ctx, beatID, feedback)
}

// SetFeedbackCalls gets all the calls that were made to SetFeedback.
// Check the length with:
//
//	len(mockedDatabase.SetFeedbackCalls())
func (mock *DatabaseMock) SetFeedbackCalls() []struct {
	Ctx      context.Context
	BeatID   int64
	Feedback string
} {
	var calls []struct {
		Ctx      context.Context
		BeatID   int64
		Feedback string
	}
	mock.lockSetFeedback.RLock()
	calls = mock.calls.SetFeedback
	mock.lockSetFeedback.RUnlock()
	return calls
}

// SetSetting calls SetSettingFunc.
func (mock *DatabaseMock) SetSetting(ctx context.Context, key string, value string) error {
	if mock.SetSettingFunc == nil {
		panic("DatabaseMock.SetSettingFunc: method is nil but Database.SetSetting was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value string
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockSetSetting.Lock()
	mock.calls.SetSetting = append(mock.calls.SetSetting, callInfo)
	mock.lockSetSetting.Unlock()
	return mock.SetSettingFunc(ctx, key, value)
}

// SetSettingCalls gets all the calls that were made to SetSetting.
// Check the length with:
//
//	len(mockedDatabase.SetSettingCalls())
func (mock *DatabaseMock) SetSettingCalls() []struct {
	Ctx   context.Context
	Key   string
	Value string
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value string
	}
	mock.lockSetSetting.RLock()
	calls = mock.calls.SetSetting
	mock.lockSetSetting.RUnlock()
	return calls
}

// SuggestTags calls SuggestTagsFunc.
func (mock *DatabaseMock) SuggestTags(ctx context.Context, prefix string, limit int) ([]string, error) {
	if mock.SuggestTagsFunc == nil {
		panic("DatabaseMock.SuggestTagsFunc: method is nil but Database.SuggestTags was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Prefix string
		Limit  int
	}{
		Ctx:    ctx,
		Prefix: prefix,
		Limit:  limit,
	}
	mock.lockSuggestTags.Lock()
	mock.calls.SuggestTags = append(mock.calls.SuggestTags, callInfo)
	mock.lockSuggestTags.Unlock()
	return mock.SuggestTagsFunc(ctx, prefix, limit)
}

// SuggestTagsCalls gets all the calls that were made to SuggestTags.
// Check the length with:
//
//	len(mockedDatabase.SuggestTagsCalls())
func (mock *DatabaseMock) SuggestTagsCalls() []struct {
	Ctx    context.Context
	Prefix string
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Prefix string
		Limit  int
	}
	mock.lockSuggestTags.RLock()
	calls = mock.calls.SuggestTags
	mock.lockSuggestTags.RUnlock()
	return calls
}

// UpdateFeed calls UpdateFeedFunc.
func (mock *DatabaseMock) UpdateFeed(ctx context.Context, feedID int64, title string, feedURL string, iconURL string, fetchInterval time.Duration) error {
	if mock.UpdateFeedFunc == nil {
		panic("DatabaseMock.UpdateFeedFunc: method is nil but Database.UpdateFeed was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		FeedID        int64
		Title         string
		FeedURL       string
		IconURL       string
		FetchInterval time.Duration
	}{
		Ctx:           ctx,
		FeedID:        feedID,
		Title:         title,
		FeedURL:       feedURL,
		IconURL:       iconURL,
		FetchInterval: fetchInterval,
	}
	mock.lockUpdateFeed.Lock()
	mock.calls.UpdateFeed = append(mock.calls.UpdateFeed, callInfo)
	mock.lockUpdateFeed.Unlock()
	return mock.UpdateFeedFunc(ctx, feedID, title, feedURL, iconURL, fetchInterval)
}

// UpdateFeedCalls gets all the calls that were made to UpdateFeed.
// Check the length with:
//
//	len(mockedDatabase.UpdateFeedCalls())
func (mock *DatabaseMock) UpdateFeedCalls() []struct {
	Ctx           context.Context
	FeedID        int64
	Title         string
	FeedURL       string
	IconURL       string
	FetchInterval time.Duration
} {
	var calls []struct {
		Ctx           context.Context
		FeedID        int64
		Title         string
		FeedURL       string
		IconURL       string
		FetchInterval time.Duration
	}
	mock.lockUpdateFeed.RLock()
	calls = mock.calls.UpdateFeed
	mock.lockUpdateFeed.RUnlock()
	return calls
}

// UpdateFeedStatus calls UpdateFeedStatusFunc.
func (mock *DatabaseMock) UpdateFeedStatus(ctx context.Context, feedID int64, enabled bool) error {
	if mock.UpdateFeedStatusFunc == nil {
		panic("DatabaseMock.UpdateFeedStatusFunc: method is nil but Database.UpdateFeedStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		FeedID  int64
		Enabled bool
	}{
		Ctx:     ctx,
		FeedID:  feedID,
		Enabled: enabled,
	}
	mock.lockUpdateFeedStatus.Lock()
	mock.calls.UpdateFeedStatus = append(mock.calls.UpdateFeedStatus, callInfo)
	mock.lockUpdateFeedStatus.Unlock()
	return mock.UpdateFeedStatusFunc(ctx, feedID, enabled)
}

// UpdateFeedStatusCalls gets all the calls that were made to UpdateFeedStatus.
// Check the length with:
//
//	len(mockedDatabase.UpdateFeedStatusCalls())
func (mock *DatabaseMock) UpdateFeedStatusCalls() []struct {
	Ctx     context.Context
	FeedID  int64
	Enabled bool
} {
	var calls []struct {
		Ctx     context.Context
		FeedID  int64
		Enabled bool
	}
	mock.lockUpdateFeedStatus.RLock()
	calls = mock.calls.UpdateFeedStatus
	mock.lockUpdateFeedStatus.RUnlock()
	return calls
}

// UpdateGrouping calls UpdateGroupingFunc.
func (mock *DatabaseMock) UpdateGrouping(ctx context.Context, g domain.Grouping) error {
	if mock.UpdateGroupingFunc == nil {
		panic("DatabaseMock.UpdateGroupingFunc: method is nil but Database.UpdateGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		G   domain.Grouping
	}{
		Ctx: ctx,
		G:   g,
	}
	mock.lockUpdateGrouping.Lock()
	mock.calls.UpdateGrouping = append(mock.calls.UpdateGrouping, callInfo)
	mock.lockUpdateGrouping.Unlock()
	return mock.UpdateGroupingFunc(ctx, g)
}

// UpdateGroupingCalls gets all the calls that were made to UpdateGrouping.
// Check the length with:
//
//	len(mockedDatabase.UpdateGroupingCalls())
func (mock *DatabaseMock) UpdateGroupingCalls() []struct {
	Ctx context.Context
	G   domain.Grouping
} {
	var calls []struct {
		Ctx context.Context
		G   domain.Grouping
	}
	mock.lockUpdateGrouping.RLock()
	calls = mock.calls.UpdateGrouping
	mock.lockUpdateGrouping.RUnlock()
	return calls
}

// UpdateItemFeedback calls UpdateItemFeedbackFunc.
func (mock *DatabaseMock) UpdateItemFeedback(ctx context.Context, itemID int64, feedback string) error {
	if mock.UpdateItemFeedbackFunc == nil {
		panic("DatabaseMock.UpdateItemFeedbackFunc: method is nil but Database.UpdateItemFeedback was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ItemID   int64
		Feedback string
	}{
		Ctx:      ctx,
		ItemID:   itemID,
		Feedback: feedback,
	}
	mock.lockUpdateItemFeedback.Lock()
	mock.calls.UpdateItemFeedback = append(mock.calls.UpdateItemFeedback, callInfo)
	mock.lockUpdateItemFeedback.Unlock()
	return mock.UpdateItemFeedbackFunc(ctx, itemID, feedback)
}

// UpdateItemFeedbackCalls gets all the calls that were made to UpdateItemFeedback.
// Check the length with:
//
//	len(mockedDatabase.UpdateItemFeedbackCalls())
func (mock *DatabaseMock) UpdateItemFeedbackCalls() []struct {
	Ctx      context.Context
	ItemID   int64
	Feedback string
} {
	var calls []struct {
		Ctx      context.Context
		ItemID   int64
		Feedback string
	}
	mock.lockUpdateItemFeedback.RLock()
	calls = mock.calls.UpdateItemFeedback
	mock.lockUpdateItemFeedback.RUnlock()
	return calls
}
