// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/domain"
)

// GroupingRepoMock is a mock implementation of server.GroupingRepo.
//
//	func TestSomethingThatUsesGroupingRepo(t *testing.T) {
//
//		// make and configure a mocked server.GroupingRepo
//		mockedGroupingRepo := &GroupingRepoMock{
//			CreateGroupingFunc: func(ctx context.Context, g domain.Grouping) (int64, error) {
//				panic("mock out the CreateGrouping method")
//			},
//			DeleteGroupingFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteGrouping method")
//			},
//			GetGroupingFunc: func(ctx context.Context, id int64) (domain.Grouping, error) {
//				panic("mock out the GetGrouping method")
//			},
//			GetGroupingBySlugFunc: func(ctx context.Context, slug string) (domain.Grouping, error) {
//				panic("mock out the GetGroupingBySlug method")
//			},
//			GroupingCountsFunc: func(ctx context.Context) (map[int64]int, error) {
//				panic("mock out the GroupingCounts method")
//			},
//			ListGroupingsFunc: func(ctx context.Context) ([]domain.Grouping, error) {
//				panic("mock out the ListGroupings method")
//			},
//			ReorderGroupingsFunc: func(ctx context.Context, idsInOrder []int64) error {
//				panic("mock out the ReorderGroupings method")
//			},
//			UpdateGroupingFunc: func(ctx context.Context, g domain.Grouping) error {
//				panic("mock out the UpdateGrouping method")
//			},
//		}
//
//		// use mockedGroupingRepo in code that requires server.GroupingRepo
//		// and then make assertions.
//
//	}
type GroupingRepoMock struct {
	// CreateGroupingFunc mocks the CreateGrouping method.
	CreateGroupingFunc func(ctx context.Context, g domain.Grouping) (int64, error)

	// DeleteGroupingFunc mocks the DeleteGrouping method.
	DeleteGroupingFunc func(ctx context.Context, id int64) error

	// GetGroupingFunc mocks the GetGrouping method.
	GetGroupingFunc func(ctx context.Context, id int64) (domain.Grouping, error)

	// GetGroupingBySlugFunc mocks the GetGroupingBySlug method.
	GetGroupingBySlugFunc func(ctx context.Context, slug string) (domain.Grouping, error)

	// GroupingCountsFunc mocks the GroupingCounts method.
	GroupingCountsFunc func(ctx context.Context) (map[int64]int, error)

	// ListGroupingsFunc mocks the ListGroupings method.
	ListGroupingsFunc func(ctx context.Context) ([]domain.Grouping, error)

	// ReorderGroupingsFunc mocks the ReorderGroupings method.
	ReorderGroupingsFunc func(ctx context.Context, idsInOrder []int64) error

	// UpdateGroupingFunc mocks the UpdateGrouping method.
	UpdateGroupingFunc func(ctx context.Context, g domain.Grouping) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateGrouping holds details about calls to the CreateGrouping method.
		CreateGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// G is the g argument value.
			G domain.Grouping
		}
		// DeleteGrouping holds details about calls to the DeleteGrouping method.
		DeleteGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetGrouping holds details about calls to the GetGrouping method.
		GetGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetGroupingBySlug holds details about calls to the GetGroupingBySlug method.
		GetGroupingBySlug []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slug is the slug argument value.
			Slug string
		}
		// GroupingCounts holds details about calls to the GroupingCounts method.
		GroupingCounts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListGroupings holds details about calls to the ListGroupings method.
		ListGroupings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReorderGroupings holds details about calls to the ReorderGroupings method.
		ReorderGroupings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdsInOrder is the idsInOrder argument value.
			IdsInOrder []int64
		}
		// UpdateGrouping holds details about calls to the UpdateGrouping method.
		UpdateGrouping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// G is the g argument value.
			G domain.Grouping
		}
	}
	lockCreateGrouping    sync.RWMutex
	lockDeleteGrouping    sync.RWMutex
	lockGetGrouping       sync.RWMutex
	lockGetGroupingBySlug sync.RWMutex
	lockGroupingCounts    sync.RWMutex
	lockListGroupings     sync.RWMutex
	lockReorderGroupings  sync.RWMutex
	lockUpdateGrouping    sync.RWMutex
}

// CreateGrouping calls CreateGroupingFunc.
func (mock *GroupingRepoMock) CreateGrouping(ctx context.Context, g domain.Grouping) (int64, error) {
	if mock.CreateGroupingFunc == nil {
		panic("GroupingRepoMock.CreateGroupingFunc: method is nil but GroupingRepo.CreateGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		G   domain.Grouping
	}{
		Ctx: ctx,
		G:   g,
	}
	mock.lockCreateGrouping.Lock()
	mock.calls.CreateGrouping = append(mock.calls.CreateGrouping, callInfo)
	mock.lockCreateGrouping.Unlock()
	return mock.CreateGroupingFunc(ctx, g)
}

// CreateGroupingCalls gets all the calls that were made to CreateGrouping.
// Check the length with:
//
//	len(mockedGroupingRepo.CreateGroupingCalls())
func (mock *GroupingRepoMock) CreateGroupingCalls() []struct {
	Ctx context.Context
	G   domain.Grouping
} {
	var calls []struct {
		Ctx context.Context
		G   domain.Grouping
	}
	mock.lockCreateGrouping.RLock()
	calls = mock.calls.CreateGrouping
	mock.lockCreateGrouping.RUnlock()
	return calls
}

// DeleteGrouping calls DeleteGroupingFunc.
func (mock *GroupingRepoMock) DeleteGrouping(ctx context.Context, id int64) error {
	if mock.DeleteGroupingFunc == nil {
		panic("GroupingRepoMock.DeleteGroupingFunc: method is nil but GroupingRepo.DeleteGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteGrouping.Lock()
	mock.calls.DeleteGrouping = append(mock.calls.DeleteGrouping, callInfo)
	mock.lockDeleteGrouping.Unlock()
	return mock.DeleteGroupingFunc(ctx, id)
}

// DeleteGroupingCalls gets all the calls that were made to DeleteGrouping.
// Check the length with:
//
//	len(mockedGroupingRepo.DeleteGroupingCalls())
func (mock *GroupingRepoMock) DeleteGroupingCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteGrouping.RLock()
	calls = mock.calls.DeleteGrouping
	mock.lockDeleteGrouping.RUnlock()
	return calls
}

// GetGrouping calls GetGroupingFunc.
func (mock *GroupingRepoMock) GetGrouping(ctx context.Context, id int64) (domain.Grouping, error) {
	if mock.GetGroupingFunc == nil {
		panic("GroupingRepoMock.GetGroupingFunc: method is nil but GroupingRepo.GetGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetGrouping.Lock()
	mock.calls.GetGrouping = append(mock.calls.GetGrouping, callInfo)
	mock.lockGetGrouping.Unlock()
	return mock.GetGroupingFunc(ctx, id)
}

// GetGroupingCalls gets all the calls that were made to GetGrouping.
// Check the length with:
//
//	len(mockedGroupingRepo.GetGroupingCalls())
func (mock *GroupingRepoMock) GetGroupingCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetGrouping.RLock()
	calls = mock.calls.GetGrouping
	mock.lockGetGrouping.RUnlock()
	return calls
}

// GetGroupingBySlug calls GetGroupingBySlugFunc.
func (mock *GroupingRepoMock) GetGroupingBySlug(ctx context.Context, slug string) (domain.Grouping, error) {
	if mock.GetGroupingBySlugFunc == nil {
		panic("GroupingRepoMock.GetGroupingBySlugFunc: method is nil but GroupingRepo.GetGroupingBySlug was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Slug string
	}{
		Ctx:  ctx,
		Slug: slug,
	}
	mock.lockGetGroupingBySlug.Lock()
	mock.calls.GetGroupingBySlug = append(mock.calls.GetGroupingBySlug, callInfo)
	mock.lockGetGroupingBySlug.Unlock()
	return mock.GetGroupingBySlugFunc(ctx, slug)
}

// GetGroupingBySlugCalls gets all the calls that were made to GetGroupingBySlug.
// Check the length with:
//
//	len(mockedGroupingRepo.GetGroupingBySlugCalls())
func (mock *GroupingRepoMock) GetGroupingBySlugCalls() []struct {
	Ctx  context.Context
	Slug string
} {
	var calls []struct {
		Ctx  context.Context
		Slug string
	}
	mock.lockGetGroupingBySlug.RLock()
	calls = mock.calls.GetGroupingBySlug
	mock.lockGetGroupingBySlug.RUnlock()
	return calls
}

// GroupingCounts calls GroupingCountsFunc.
func (mock *GroupingRepoMock) GroupingCounts(ctx context.Context) (map[int64]int, error) {
	if mock.GroupingCountsFunc == nil {
		panic("GroupingRepoMock.GroupingCountsFunc: method is nil but GroupingRepo.GroupingCounts was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGroupingCounts.Lock()
	mock.calls.GroupingCounts = append(mock.calls.GroupingCounts, callInfo)
	mock.lockGroupingCounts.Unlock()
	return mock.GroupingCountsFunc(ctx)
}

// GroupingCountsCalls gets all the calls that were made to GroupingCounts.
// Check the length with:
//
//	len(mockedGroupingRepo.GroupingCountsCalls())
func (mock *GroupingRepoMock) GroupingCountsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGroupingCounts.RLock()
	calls = mock.calls.GroupingCounts
	mock.lockGroupingCounts.RUnlock()
	return calls
}

// ListGroupings calls ListGroupingsFunc.
func (mock *GroupingRepoMock) ListGroupings(ctx context.Context) ([]domain.Grouping, error) {
	if mock.ListGroupingsFunc == nil {
		panic("GroupingRepoMock.ListGroupingsFunc: method is nil but GroupingRepo.ListGroupings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListGroupings.Lock()
	mock.calls.ListGroupings = append(mock.calls.ListGroupings, callInfo)
	mock.lockListGroupings.Unlock()
	return mock.ListGroupingsFunc(ctx)
}

// ListGroupingsCalls gets all the calls that were made to ListGroupings.
// Check the length with:
//
//	len(mockedGroupingRepo.ListGroupingsCalls())
func (mock *GroupingRepoMock) ListGroupingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListGroupings.RLock()
	calls = mock.calls.ListGroupings
	mock.lockListGroupings.RUnlock()
	return calls
}

// ReorderGroupings calls ReorderGroupingsFunc.
func (mock *GroupingRepoMock) ReorderGroupings(ctx context.Context, idsInOrder []int64) error {
	if mock.ReorderGroupingsFunc == nil {
		panic("GroupingRepoMock.ReorderGroupingsFunc: method is nil but GroupingRepo.ReorderGroupings was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		IdsInOrder []int64
	}{
		Ctx:        ctx,
		IdsInOrder: idsInOrder,
	}
	mock.lockReorderGroupings.Lock()
	mock.calls.ReorderGroupings = append(mock.calls.ReorderGroupings, callInfo)
	mock.lockReorderGroupings.Unlock()
	return mock.ReorderGroupingsFunc(ctx, idsInOrder)
}

// ReorderGroupingsCalls gets all the calls that were made to ReorderGroupings.
// Check the length with:
//
//	len(mockedGroupingRepo.ReorderGroupingsCalls())
func (mock *GroupingRepoMock) ReorderGroupingsCalls() []struct {
	Ctx        context.Context
	IdsInOrder []int64
} {
	var calls []struct {
		Ctx        context.Context
		IdsInOrder []int64
	}
	mock.lockReorderGroupings.RLock()
	calls = mock.calls.ReorderGroupings
	mock.lockReorderGroupings.RUnlock()
	return calls
}

// UpdateGrouping calls UpdateGroupingFunc.
func (mock *GroupingRepoMock) UpdateGrouping(ctx context.Context, g domain.Grouping) error {
	if mock.UpdateGroupingFunc == nil {
		panic("GroupingRepoMock.UpdateGroupingFunc: method is nil but GroupingRepo.UpdateGrouping was just called")
	}
	callInfo := struct {
		Ctx context.Context
		G   domain.Grouping
	}{
		Ctx: ctx,
		G:   g,
	}
	mock.lockUpdateGrouping.Lock()
	mock.calls.UpdateGrouping = append(mock.calls.UpdateGrouping, callInfo)
	mock.lockUpdateGrouping.Unlock()
	return mock.UpdateGroupingFunc(ctx, g)
}

// UpdateGroupingCalls gets all the calls that were made to UpdateGrouping.
// Check the length with:
//
//	len(mockedGroupingRepo.UpdateGroupingCalls())
func (mock *GroupingRepoMock) UpdateGroupingCalls() []struct {
	Ctx context.Context
	G   domain.Grouping
} {
	var calls []struct {
		Ctx context.Context
		G   domain.Grouping
	}
	mock.lockUpdateGrouping.RLock()
	calls = mock.calls.UpdateGrouping
	mock.lockUpdateGrouping.RUnlock()
	return calls
}
